[assembly: System.Reflection.AssemblyDescription("RazorEngine - Core Framework")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Runtime.InteropServices.Guid("C11064C2-11B8-420B-81F0-4C6477CB5931")]
[assembly: System.Reflection.AssemblyAlgorithmId(System.Configuration.Assemblies.AssemblyHashAlgorithm.MD5)]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1005:可简化委托调用。", Justification = "<挂起>")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:删除未使用的参数", Justification = "<挂起>")]
