//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basic.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Basic.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 读取配置文件异常，可能是配置文件路径不正确或配置文件被移动，配置文件名称{0}。 的本地化字符串。
        /// </summary>
        internal static string Access_ConfigFileException {
            get {
                return ResourceManager.GetString("Access_ConfigFileException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取配置文件异常，配置文件&quot;{0}&quot;中，不存在类型为&quot;{1}&quot;的数据库连接配置信息。 的本地化字符串。
        /// </summary>
        internal static string Access_Configuration_ConnectionError {
            get {
                return ResourceManager.GetString("Access_Configuration_ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取配置文件异常，配置文件&quot;{0}&quot;不存在。 的本地化字符串。
        /// </summary>
        internal static string Access_Configuration_FileNotFound {
            get {
                return ResourceManager.GetString("Access_Configuration_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取配置文件异常，配置文件&quot;{0}&quot;中，不存在自定义配置组&quot;{1}&apos;。 的本地化字符串。
        /// </summary>
        internal static string Access_Configuration_GroupNotFound {
            get {
                return ResourceManager.GetString("Access_Configuration_GroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取配置文件异常，配置文件&quot;{0}&quot;中，不存在数据库连接配置信息或默认连接信息。 的本地化字符串。
        /// </summary>
        internal static string Access_Configuration_SectionsError {
            get {
                return ResourceManager.GetString("Access_Configuration_SectionsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取配置文件异常，配置文件&quot;{0}&quot;中，自定义配置组&quot;{1}&quot;，类型必须是&quot;{2}&quot;。 的本地化字符串。
        /// </summary>
        internal static string Access_Configuration_SectionTypeError {
            get {
                return ResourceManager.GetString("Access_Configuration_SectionTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类{0}不存在自定义属性{1}，无法获取配置文件信息。 的本地化字符串。
        /// </summary>
        internal static string Access_ConfigurationAttribute {
            get {
                return ResourceManager.GetString("Access_ConfigurationAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数类型错误，参数类型必须是AbstractAccess的子类。 的本地化字符串。
        /// </summary>
        internal static string Access_ConfigurationParameterType {
            get {
                return ResourceManager.GetString("Access_ConfigurationParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 构造函数使用错误，请使用带参数的构造函数创建{0}类型的实例 的本地化字符串。
        /// </summary>
        internal static string Access_ConstructedFunction {
            get {
                return ResourceManager.GetString("Access_ConstructedFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transact-SQL语句结构&quot;{0}&quot;设置错误，使用动态参数时CommandType必须是CommandType.Text枚举值。 的本地化字符串。
        /// </summary>
        internal static string Access_DynamicParameter {
            get {
                return ResourceManager.GetString("Access_DynamicParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数&apos;{0}&apos;无效，请检查程序是否使用了错误的数据库配置信息。 的本地化字符串。
        /// </summary>
        internal static string Access_InvalidArgument {
            get {
                return ResourceManager.GetString("Access_InvalidArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transact-SQL语句结构&quot;{0}&quot;设置错误，如果启用动态参数必须将DynamicParameter设置为True。 的本地化字符串。
        /// </summary>
        internal static string Access_MustDynamicParameter {
            get {
                return ResourceManager.GetString("Access_MustDynamicParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 构造函数参数错误,类型{0}必须有无参构造函数。 的本地化字符串。
        /// </summary>
        internal static string Access_NoParameterConstructor {
            get {
                return ResourceManager.GetString("Access_NoParameterConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; 命令中 缺少 Order By子句，如果需要分页则必须需要此子句。 的本地化字符串。
        /// </summary>
        internal static string Access_NotExist_OrderBy {
            get {
                return ResourceManager.GetString("Access_NotExist_OrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体类{0}中不存在属性{1}。 的本地化字符串。
        /// </summary>
        internal static string Access_NotExistProperty {
            get {
                return ResourceManager.GetString("Access_NotExistProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类{0}中配置信息错误,名称为{1}的连接配置信息不存在，请检查应用程序配置文件(*.config) 的本地化字符串。
        /// </summary>
        internal static string Access_NotExistsConnection {
            get {
                return ResourceManager.GetString("Access_NotExistsConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置文件中不存在配置节:{0}，请检查配置节名称。 的本地化字符串。
        /// </summary>
        internal static string Access_NotExistsElement {
            get {
                return ResourceManager.GetString("Access_NotExistsElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前参数{0}不能为空或参数中字段个数不能为零。 的本地化字符串。
        /// </summary>
        internal static string Access_Parameter_IStringObjectArray {
            get {
                return ResourceManager.GetString("Access_Parameter_IStringObjectArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前使用了不支持的数据库参数类型，类型&quot;{0}.{1}&quot;无效。 的本地化字符串。
        /// </summary>
        internal static string Access_ParameterType_UnSupport {
            get {
                return ResourceManager.GetString("Access_ParameterType_UnSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体类{0}的属性{1},禁止读取数据。 的本地化字符串。
        /// </summary>
        internal static string Access_PropertyForbidRead {
            get {
                return ResourceManager.GetString("Access_PropertyForbidRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体类{0}的属性{1},禁止修改数据。 的本地化字符串。
        /// </summary>
        internal static string Access_PropertyForbidWrite {
            get {
                return ResourceManager.GetString("Access_PropertyForbidWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建关键字出错，没有指定关键字列名或指定的列名错误 的本地化字符串。
        /// </summary>
        internal static string Access_ReturnColumn {
            get {
                return ResourceManager.GetString("Access_ReturnColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The argument &apos;{0}&apos; cannot be null, empty or contain only white space. 的本地化字符串。
        /// </summary>
        internal static string ArgumentIsNullOrWhitespace {
            get {
                return ResourceManager.GetString("ArgumentIsNullOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体类{0}中未找到{1}类的特性信息，因此无法进行任何数据库读、写、删。 的本地化字符串。
        /// </summary>
        internal static string BaseEntityType_AccessConfigurationAttribute {
            get {
                return ResourceManager.GetString("BaseEntityType_AccessConfigurationAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表{0}中缺少主键信息。 的本地化字符串。
        /// </summary>
        internal static string BaseEntityType_MissingPrimaryKey {
            get {
                return ResourceManager.GetString("BaseEntityType_MissingPrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A value for &apos;{0}&apos; is required but was not present in the request. 的本地化字符串。
        /// </summary>
        internal static string BindingBehavior_ValueNotFound {
            get {
                return ResourceManager.GetString("BindingBehavior_ValueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The &apos;Duration&apos; property must be a positive number. 的本地化字符串。
        /// </summary>
        internal static string ChildActionCacheAttribute_DurationMustBePositive {
            get {
                return ResourceManager.GetString("ChildActionCacheAttribute_DurationMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型&apos;{0}&apos;的属性&apos;{1}&apos;中不存在ColumnMappingAttribute特性标记 的本地化字符串。
        /// </summary>
        internal static string ColumnAttribute_NotExists {
            get {
                return ResourceManager.GetString("ColumnAttribute_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型&apos;{0}&apos;的属性&apos;{1}&apos;中不存在ColumnMappingAttribute特性标记 的本地化字符串。
        /// </summary>
        internal static string ColumnMappingAttribute_NotExists {
            get {
                return ResourceManager.GetString("ColumnMappingAttribute_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This model binder does not support the model type &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string Common_ModelBinderDoesNotSupportModelType {
            get {
                return ResourceManager.GetString("Common_ModelBinderDoesNotSupportModelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value cannot be null or empty. 的本地化字符串。
        /// </summary>
        internal static string Common_NullOrEmpty {
            get {
                return ResourceManager.GetString("Common_NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The property {0}.{1} could not be found. 的本地化字符串。
        /// </summary>
        internal static string Common_PropertyNotFound {
            get {
                return ResourceManager.GetString("Common_PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; does not implement the interface &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string Common_TypeMustImplementInterface {
            get {
                return ResourceManager.GetString("Common_TypeMustImplementInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The &apos;Name&apos; property must be set. 的本地化字符串。
        /// </summary>
        internal static string CommonControls_NameRequired {
            get {
                return ResourceManager.GetString("CommonControls_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; and &apos;{1}&apos; do not match. 的本地化字符串。
        /// </summary>
        internal static string CompareAttribute_MustMatch {
            get {
                return ResourceManager.GetString("CompareAttribute_MustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性名:{0}，类型:{1} 的本地化字符串。
        /// </summary>
        internal static string ConnectionSectionProperty {
            get {
                return ResourceManager.GetString("ConnectionSectionProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection配置节可用的属性有,请参考以下可用属性列表： 的本地化字符串。
        /// </summary>
        internal static string ConnectionSectionPropertyError {
            get {
                return ResourceManager.GetString("ConnectionSectionPropertyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库连接类型枚举 的本地化字符串。
        /// </summary>
        internal static string ConnectionType_Description {
            get {
                return ResourceManager.GetString("ConnectionType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OdbcConnection类型数据库连接 的本地化字符串。
        /// </summary>
        internal static string ConnectionType_OdbcConType {
            get {
                return ResourceManager.GetString("ConnectionType_OdbcConType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OleDbConnection类型数据库连接 的本地化字符串。
        /// </summary>
        internal static string ConnectionType_OleDbConType {
            get {
                return ResourceManager.GetString("ConnectionType_OleDbConType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OracleConnection类型数据库连接 的本地化字符串。
        /// </summary>
        internal static string ConnectionType_OracleConType {
            get {
                return ResourceManager.GetString("ConnectionType_OracleConType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SqlConnection类型数据库连接 的本地化字符串。
        /// </summary>
        internal static string ConnectionType_SqlConType {
            get {
                return ResourceManager.GetString("ConnectionType_SqlConType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SQLiteConnection类型数据库连接 的本地化字符串。
        /// </summary>
        internal static string ConnectionType_SQLiteConType {
            get {
                return ResourceManager.GetString("ConnectionType_SQLiteConType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The IControllerFactory &apos;{0}&apos; did not return a controller for a controller named &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ControllerBuilder_FactoryReturnedNull {
            get {
                return ResourceManager.GetString("ControllerBuilder_FactoryReturnedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} field is not a valid credit card number. 的本地化字符串。
        /// </summary>
        internal static string CreditCardAttribute_Invalid {
            get {
                return ResourceManager.GetString("CreditCardAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} field is not a valid CUIT number. 的本地化字符串。
        /// </summary>
        internal static string CuitAttribute_Invalid {
            get {
                return ResourceManager.GetString("CuitAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} has a DisplayColumn attribute for {1}, but property {1} does not exist. 的本地化字符串。
        /// </summary>
        internal static string DataAnnotationsModelMetadataProvider_UnknownProperty {
            get {
                return ResourceManager.GetString("DataAnnotationsModelMetadataProvider_UnknownProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} has a DisplayColumn attribute for {1}, but property {1} does not have a public getter. 的本地化字符串。
        /// </summary>
        internal static string DataAnnotationsModelMetadataProvider_UnreadableProperty {
            get {
                return ResourceManager.GetString("DataAnnotationsModelMetadataProvider_UnreadableProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Access类型数据库 的本地化字符串。
        /// </summary>
        internal static string DataBaseType_Access {
            get {
                return ResourceManager.GetString("DataBaseType_Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM公司DB2类型数据库 的本地化字符串。
        /// </summary>
        internal static string DataBaseType_DB2 {
            get {
                return ResourceManager.GetString("DataBaseType_DB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库连接类型枚举 的本地化字符串。
        /// </summary>
        internal static string DataBaseType_Description {
            get {
                return ResourceManager.GetString("DataBaseType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Oracle类型数据库 的本地化字符串。
        /// </summary>
        internal static string DataBaseType_Oracle {
            get {
                return ResourceManager.GetString("DataBaseType_Oracle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SQLite类型数据库 的本地化字符串。
        /// </summary>
        internal static string DataBaseType_SQLite {
            get {
                return ResourceManager.GetString("DataBaseType_SQLite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SQL SERVER类型数据库 的本地化字符串。
        /// </summary>
        internal static string DataBaseType_SqlServer {
            get {
                return ResourceManager.GetString("DataBaseType_SqlServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DataReader: 类中&apos;{0}&apos;中不存在属性&apos;{1}&apos; 的本地化字符串。
        /// </summary>
        internal static string DataReader_Prop_Not_Found {
            get {
                return ResourceManager.GetString("DataReader_Prop_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is not a valid date 的本地化字符串。
        /// </summary>
        internal static string DateAttribute_Invalid {
            get {
                return ResourceManager.GetString("DateAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} should contain only digits 的本地化字符串。
        /// </summary>
        internal static string DigitsAttribute_Invalid {
            get {
                return ResourceManager.GetString("DigitsAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sample Item 的本地化字符串。
        /// </summary>
        internal static string DropDownList_SampleItem {
            get {
                return ResourceManager.GetString("DropDownList_SampleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DynamicViewDataDictionary only supports single indexers. 的本地化字符串。
        /// </summary>
        internal static string DynamicViewDataDictionary_SingleIndexerOnly {
            get {
                return ResourceManager.GetString("DynamicViewDataDictionary_SingleIndexerOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DynamicViewDataDictionary only supports string-based indexers. 的本地化字符串。
        /// </summary>
        internal static string DynamicViewDataDictionary_StringIndexerOnly {
            get {
                return ResourceManager.GetString("DynamicViewDataDictionary_StringIndexerOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The property {0} doesn&apos;t exist. There are no public properties on this object. 的本地化字符串。
        /// </summary>
        internal static string DynamicViewPage_NoProperties {
            get {
                return ResourceManager.GetString("DynamicViewPage_NoProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The property {0} doesn&apos;t exist. Supported properties are: {1}. 的本地化字符串。
        /// </summary>
        internal static string DynamicViewPage_PropertyDoesNotExist {
            get {
                return ResourceManager.GetString("DynamicViewPage_PropertyDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} field is not a valid e-mail address. 的本地化字符串。
        /// </summary>
        internal static string EmailAddressAttribute_Invalid {
            get {
                return ResourceManager.GetString("EmailAddressAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名为&quot;{0}&quot;的属性值类型与目标值类型&quot;{1}&quot;不相同，无法进行值相等比较。 的本地化字符串。
        /// </summary>
        internal static string ErrorPropertyType {
            get {
                return ResourceManager.GetString("ErrorPropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The method &apos;{0}&apos; is an asynchronous completion method and cannot be called directly. 的本地化字符串。
        /// </summary>
        internal static string ExpressionHelper_CannotCallCompletedMethod {
            get {
                return ResourceManager.GetString("ExpressionHelper_CannotCallCompletedMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The method &apos;{0}&apos; is marked [NonAction] and cannot be called directly. 的本地化字符串。
        /// </summary>
        internal static string ExpressionHelper_CannotCallNonAction {
            get {
                return ResourceManager.GetString("ExpressionHelper_CannotCallNonAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot route to class named &apos;Controller&apos;. 的本地化字符串。
        /// </summary>
        internal static string ExpressionHelper_CannotRouteToController {
            get {
                return ResourceManager.GetString("ExpressionHelper_CannotRouteToController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expression must be a method call. 的本地化字符串。
        /// </summary>
        internal static string ExpressionHelper_MustBeMethodCall {
            get {
                return ResourceManager.GetString("ExpressionHelper_MustBeMethodCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controller name must end in &apos;Controller&apos;. 的本地化字符串。
        /// </summary>
        internal static string ExpressionHelper_TargetMustEndInController {
            get {
                return ResourceManager.GetString("ExpressionHelper_TargetMustEndInController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The new model binding system cannot be used when a property whitelist or blacklist has been specified in [Bind] or via the call to UpdateModel() / TryUpdateModel(). Use the [BindRequired] and [BindNever] attributes on the model type or its properties instead. 的本地化字符串。
        /// </summary>
        internal static string ExtensibleModelBinderAdapter_PropertyFilterMustNotBeSet {
            get {
                return ResourceManager.GetString("ExtensibleModelBinderAdapter_PropertyFilterMustNotBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} field only accepts files with the following extensions: {1} 的本地化字符串。
        /// </summary>
        internal static string FileExtensionsAttribute_Invalid {
            get {
                return ResourceManager.GetString("FileExtensionsAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; is not an open generic type. 的本地化字符串。
        /// </summary>
        internal static string GenericModelBinderProvider_ParameterMustSpecifyOpenGenericType {
            get {
                return ResourceManager.GetString("GenericModelBinderProvider_ParameterMustSpecifyOpenGenericType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The open model type &apos;{0}&apos; has {1} generic type argument(s), but the open binder type &apos;{2}&apos; has {3} generic type argument(s). The binder type must not be an open generic type or must have the same number of generic arguments as the open model type. 的本地化字符串。
        /// </summary>
        internal static string GenericModelBinderProvider_TypeArgumentCountMismatch {
            get {
                return ResourceManager.GetString("GenericModelBinderProvider_TypeArgumentCountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化GridView列时，不能讲HeaderText和HeaderCode同时设置Null值，这会导致GridView不能正确显示表头。 的本地化字符串。
        /// </summary>
        internal static string GridViewColumn_HeaderText_Null {
            get {
                return ResourceManager.GetString("GridViewColumn_HeaderText_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no ViewData item with the key &apos;{0}&apos; of type &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string HtmlHelper_MissingSelectData {
            get {
                return ResourceManager.GetString("HtmlHelper_MissingSelectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The ViewData item with the key &apos;{0}&apos; is of type &apos;{1}&apos; but needs to be of type &apos;{2}&apos;. 的本地化字符串。
        /// </summary>
        internal static string HtmlHelper_WrongSelectDataType {
            get {
                return ResourceManager.GetString("HtmlHelper_WrongSelectDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库参数:&quot;{0}&quot;需要值，当前参入参数中不存在此参数需要的值。 的本地化字符串。
        /// </summary>
        internal static string IDataPersistent_ParameterValue {
            get {
                return ResourceManager.GetString("IDataPersistent_ParameterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前数据库命令没有被初始化，请在执行数据库命令前首先确保调用InitCommand(SqlStruct)方法，或者调用InitCommand(SqlStruct)时，参数不正确。 的本地化字符串。
        /// </summary>
        internal static string IDataPersistent_UninitializedCommand {
            get {
                return ResourceManager.GetString("IDataPersistent_UninitializedCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的方法，类{0}不能使用此方法。 的本地化字符串。
        /// </summary>
        internal static string IDataPersistent_UselessMethod {
            get {
                return ResourceManager.GetString("IDataPersistent_UselessMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} should be a positive or negative non-decimal number. 的本地化字符串。
        /// </summary>
        internal static string IntegerAttribute_Invalid {
            get {
                return ResourceManager.GetString("IntegerAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type &apos;{0}&apos; is not supported for deserialization of an array. 的本地化字符串。
        /// </summary>
        internal static string JSON_ArrayTypeNotSupported {
            get {
                return ResourceManager.GetString("JSON_ArrayTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unrecognized escape sequence. 的本地化字符串。
        /// </summary>
        internal static string JSON_BadEscape {
            get {
                return ResourceManager.GetString("JSON_BadEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot convert object of type &apos;{0}&apos; to type &apos;{1}&apos; 的本地化字符串。
        /// </summary>
        internal static string JSON_CannotConvertObjectToType {
            get {
                return ResourceManager.GetString("JSON_CannotConvertObjectToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot create instance of {0}. 的本地化字符串。
        /// </summary>
        internal static string JSON_CannotCreateListType {
            get {
                return ResourceManager.GetString("JSON_CannotCreateListType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A circular reference was detected while serializing an object of type &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string JSON_CircularReference {
            get {
                return ResourceManager.GetString("JSON_CircularReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RecursionLimit exceeded. 的本地化字符串。
        /// </summary>
        internal static string JSON_DepthLimitExceeded {
            get {
                return ResourceManager.GetString("JSON_DepthLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot deserialize object graph into type of &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string JSON_DeserializerTypeMismatch {
            get {
                return ResourceManager.GetString("JSON_DeserializerTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type &apos;{0}&apos; is not supported for serialization/deserialization of a dictionary, keys must be strings or objects. 的本地化字符串。
        /// </summary>
        internal static string JSON_DictionaryTypeNotSupported {
            get {
                return ResourceManager.GetString("JSON_DictionaryTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid object passed in, &apos;{&apos; expected. 的本地化字符串。
        /// </summary>
        internal static string JSON_ExpectedOpenBrace {
            get {
                return ResourceManager.GetString("JSON_ExpectedOpenBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid JSON primitive: {0}. 的本地化字符串。
        /// </summary>
        internal static string JSON_IllegalPrimitive {
            get {
                return ResourceManager.GetString("JSON_IllegalPrimitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid array passed in, &apos;]&apos; expected. 的本地化字符串。
        /// </summary>
        internal static string JSON_InvalidArrayEnd {
            get {
                return ResourceManager.GetString("JSON_InvalidArrayEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid array passed in, &apos;,&apos; expected. 的本地化字符串。
        /// </summary>
        internal static string JSON_InvalidArrayExpectComma {
            get {
                return ResourceManager.GetString("JSON_InvalidArrayExpectComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid array passed in, extra trailing &apos;,&apos;. 的本地化字符串。
        /// </summary>
        internal static string JSON_InvalidArrayExtraComma {
            get {
                return ResourceManager.GetString("JSON_InvalidArrayExtraComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid array passed in, &apos;[&apos; expected. 的本地化字符串。
        /// </summary>
        internal static string JSON_InvalidArrayStart {
            get {
                return ResourceManager.GetString("JSON_InvalidArrayStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enums based on System.Int64 or System.UInt64 are not JSON-serializable because JavaScript does not support the necessary precision. 的本地化字符串。
        /// </summary>
        internal static string JSON_InvalidEnumType {
            get {
                return ResourceManager.GetString("JSON_InvalidEnumType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value must be a positive integer. 的本地化字符串。
        /// </summary>
        internal static string JSON_InvalidMaxJsonLength {
            get {
                return ResourceManager.GetString("JSON_InvalidMaxJsonLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid object passed in, member name expected. 的本地化字符串。
        /// </summary>
        internal static string JSON_InvalidMemberName {
            get {
                return ResourceManager.GetString("JSON_InvalidMemberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid object passed in, &apos;:&apos; or &apos;}&apos; expected. 的本地化字符串。
        /// </summary>
        internal static string JSON_InvalidObject {
            get {
                return ResourceManager.GetString("JSON_InvalidObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RecursionLimit must be a positive integer. 的本地化字符串。
        /// </summary>
        internal static string JSON_InvalidRecursionLimit {
            get {
                return ResourceManager.GetString("JSON_InvalidRecursionLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error during serialization or deserialization using the JSON JavaScriptSerializer. The length of the string exceeds the value set on the maxJsonLength property. 的本地化字符串。
        /// </summary>
        internal static string JSON_MaxJsonLengthExceeded {
            get {
                return ResourceManager.GetString("JSON_MaxJsonLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No parameterless constructor defined for type of &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string JSON_NoConstructor {
            get {
                return ResourceManager.GetString("JSON_NoConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid string passed in, &apos;\&quot;&apos; expected. 的本地化字符串。
        /// </summary>
        internal static string JSON_StringNotQuoted {
            get {
                return ResourceManager.GetString("JSON_StringNotQuoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unterminated string passed in. 的本地化字符串。
        /// </summary>
        internal static string JSON_UnterminatedString {
            get {
                return ResourceManager.GetString("JSON_UnterminatedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot convert null to a value type. 的本地化字符串。
        /// </summary>
        internal static string JSON_ValueTypeCannotBeNull {
            get {
                return ResourceManager.GetString("JSON_ValueTypeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段&quot;{0}&quot;的长度必须小于或等于&quot;{1}&quot;。 的本地化字符串。
        /// </summary>
        internal static string MaxAttribute_Invalid {
            get {
                return ResourceManager.GetString("MaxAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MaxLengthAttribute必须有一个长度值大于零。如果不限制最大长度，请删除此验证特性。 的本地化字符串。
        /// </summary>
        internal static string MaxLengthAttribute_InvalidMaxLength {
            get {
                return ResourceManager.GetString("MaxLengthAttribute_InvalidMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段“{0}”必须是一个字符串或者数组类型“{1}”的最大长度。 的本地化字符串。
        /// </summary>
        internal static string MaxLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("MaxLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义消息转换器类型&quot;{0}&quot;加载失败，请检查类型是否填写错误或程序集不存在。 的本地化字符串。
        /// </summary>
        internal static string Message_ConverterType_Error {
            get {
                return ResourceManager.GetString("Message_ConverterType_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} must be greater than or equal to {1} 的本地化字符串。
        /// </summary>
        internal static string MinAttribute_Invalid {
            get {
                return ResourceManager.GetString("MinAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MinLengthAttribute must have a Length value that is zero or greater. 的本地化字符串。
        /// </summary>
        internal static string MinLengthAttribute_InvalidMinLength {
            get {
                return ResourceManager.GetString("MinLengthAttribute_InvalidMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} must be a string or array type with a minimum length of &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string MinLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("MinLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value &apos;{0}&apos; is not valid for {1}. 的本地化字符串。
        /// </summary>
        internal static string ModelBinderConfig_ValueInvalid {
            get {
                return ResourceManager.GetString("ModelBinderConfig_ValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A value is required. 的本地化字符串。
        /// </summary>
        internal static string ModelBinderConfig_ValueRequired {
            get {
                return ResourceManager.GetString("ModelBinderConfig_ValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A binder for type {0} could not be located. 的本地化字符串。
        /// </summary>
        internal static string ModelBinderProviderCollection_BinderForTypeNotFound {
            get {
                return ResourceManager.GetString("ModelBinderProviderCollection_BinderForTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; does not subclass {1} or implement the interface {2}. 的本地化字符串。
        /// </summary>
        internal static string ModelBinderProviderCollection_InvalidBinderType {
            get {
                return ResourceManager.GetString("ModelBinderProviderCollection_InvalidBinderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The model of type &apos;{0}&apos; has a [Bind] attribute. The new model binding system cannot be used with models that have type-level [Bind] attributes. Use the [BindRequired] and [BindNever] attributes on the model type or its properties instead. 的本地化字符串。
        /// </summary>
        internal static string ModelBinderProviderCollection_TypeCannotHaveBindAttribute {
            get {
                return ResourceManager.GetString("ModelBinderProviderCollection_TypeCannotHaveBindAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The binding context has a null Model, but this binder requires a non-null model of type &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ModelBinderUtil_ModelCannotBeNull {
            get {
                return ResourceManager.GetString("ModelBinderUtil_ModelCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The binding context has a Model of type &apos;{0}&apos;, but this binder can only operate on models of type &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ModelBinderUtil_ModelInstanceIsWrong {
            get {
                return ResourceManager.GetString("ModelBinderUtil_ModelInstanceIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The binding context cannot have a null ModelMetadata. 的本地化字符串。
        /// </summary>
        internal static string ModelBinderUtil_ModelMetadataCannotBeNull {
            get {
                return ResourceManager.GetString("ModelBinderUtil_ModelMetadataCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The binding context has a ModelType of &apos;{0}&apos;, but this binder can only operate on models of type &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ModelBinderUtil_ModelTypeIsWrong {
            get {
                return ResourceManager.GetString("ModelBinderUtil_ModelTypeIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The ModelMetadata property must be set before accessing this property. 的本地化字符串。
        /// </summary>
        internal static string ModelBindingContext_ModelMetadataMustBeSet {
            get {
                return ResourceManager.GetString("ModelBindingContext_ModelMetadataMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The ControllerBuilder must return an IControllerFactory of type {0} if the MvcDynamicSessionModule is enabled. 的本地化字符串。
        /// </summary>
        internal static string MvcDynamicSessionModule_WrongControllerFactory {
            get {
                return ResourceManager.GetString("MvcDynamicSessionModule_WrongControllerFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deserialization failed. Verify that the data is being deserialized using the same SerializationMode with which it was serialized. Otherwise see the inner exception. 的本地化字符串。
        /// </summary>
        internal static string MvcSerializer_DeserializationFailed {
            get {
                return ResourceManager.GetString("MvcSerializer_DeserializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The provided SerializationMode is invalid. 的本地化字符串。
        /// </summary>
        internal static string MvcSerializer_InvalidSerializationMode {
            get {
                return ResourceManager.GetString("MvcSerializer_InvalidSerializationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The data being serialized is corrupt. 的本地化字符串。
        /// </summary>
        internal static string MvcSerializer_MagicHeaderCheckFailed {
            get {
                return ResourceManager.GetString("MvcSerializer_MagicHeaderCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统不支持的此类型{0}。 的本地化字符串。
        /// </summary>
        internal static string NonSupport_Class {
            get {
                return ResourceManager.GetString("NonSupport_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统不支持的此枚举{0}的{1}值。 的本地化字符串。
        /// </summary>
        internal static string NonSupport_Enum {
            get {
                return ResourceManager.GetString("NonSupport_Enum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统不支持的此类型{0}中{1}方法的使用。 的本地化字符串。
        /// </summary>
        internal static string NonSupport_Method {
            get {
                return ResourceManager.GetString("NonSupport_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} field is not a valid number. 的本地化字符串。
        /// </summary>
        internal static string NumericAttribute_Invalid {
            get {
                return ResourceManager.GetString("NumericAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前窗口执行新增操作。 的本地化字符串。
        /// </summary>
        internal static string OperatorModeEnum_AddNew {
            get {
                return ResourceManager.GetString("OperatorModeEnum_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前窗口执行自定义操作。 的本地化字符串。
        /// </summary>
        internal static string OperatorModeEnum_Custom {
            get {
                return ResourceManager.GetString("OperatorModeEnum_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前窗口执行删除操作。 的本地化字符串。
        /// </summary>
        internal static string OperatorModeEnum_Delete {
            get {
                return ResourceManager.GetString("OperatorModeEnum_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口操作模式枚举,一般用在页面操作中。 的本地化字符串。
        /// </summary>
        internal static string OperatorModeEnum_Des {
            get {
                return ResourceManager.GetString("OperatorModeEnum_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前窗口执行导出操作。 的本地化字符串。
        /// </summary>
        internal static string OperatorModeEnum_Export {
            get {
                return ResourceManager.GetString("OperatorModeEnum_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前窗口执行导入操作。 的本地化字符串。
        /// </summary>
        internal static string OperatorModeEnum_Import {
            get {
                return ResourceManager.GetString("OperatorModeEnum_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无任何操作。 的本地化字符串。
        /// </summary>
        internal static string OperatorModeEnum_None {
            get {
                return ResourceManager.GetString("OperatorModeEnum_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前窗口执行保存操作。 的本地化字符串。
        /// </summary>
        internal static string OperatorModeEnum_Save {
            get {
                return ResourceManager.GetString("OperatorModeEnum_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前窗口执行查询操作。 的本地化字符串。
        /// </summary>
        internal static string OperatorModeEnum_Search {
            get {
                return ResourceManager.GetString("OperatorModeEnum_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前窗口执行更新操作。 的本地化字符串。
        /// </summary>
        internal static string OperatorModeEnum_Update {
            get {
                return ResourceManager.GetString("OperatorModeEnum_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分页数据源如果为{0}模式时，不能取{1}属性的值！ 的本地化字符串。
        /// </summary>
        internal static string PagedDataSource_PagedMode_Count {
            get {
                return ResourceManager.GetString("PagedDataSource_PagedMode_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数的值为空时使用的默认值。 的本地化字符串。
        /// </summary>
        internal static string Parameter_DefaultValue {
            get {
                return ResourceManager.GetString("Parameter_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，该值指示参数是只可输入、只可输出、双向还是存储过程返回值参数。 的本地化字符串。
        /// </summary>
        internal static string Parameter_Direction {
            get {
                return ResourceManager.GetString("Parameter_Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，该值指示参数是否接受空值 的本地化字符串。
        /// </summary>
        internal static string Parameter_IsNullable {
            get {
                return ResourceManager.GetString("Parameter_IsNullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置列中数据的最大大小（以字节为单位）。 的本地化字符串。
        /// </summary>
        internal static string Parameter_Length {
            get {
                return ResourceManager.GetString("Parameter_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数的名称。 的本地化字符串。
        /// </summary>
        internal static string Parameter_Name {
            get {
                return ResourceManager.GetString("Parameter_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符串参数“{0}”不能为 Null 或为空。 的本地化字符串。
        /// </summary>
        internal static string Parameter_NullOrEmpty {
            get {
                return ResourceManager.GetString("Parameter_NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，该值指示参数数据库参数的类型。 的本地化字符串。
        /// </summary>
        internal static string Parameter_ParameterType {
            get {
                return ResourceManager.GetString("Parameter_ParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置数据库参数值解析为的小数位数 的本地化字符串。
        /// </summary>
        internal static string Parameter_Scale {
            get {
                return ResourceManager.GetString("Parameter_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数的最大大小。 的本地化字符串。
        /// </summary>
        internal static string Parameter_Size {
            get {
                return ResourceManager.GetString("Parameter_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数的类型。 的本地化字符串。
        /// </summary>
        internal static string Parameter_Type {
            get {
                return ResourceManager.GetString("Parameter_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} field is required. 的本地化字符串。
        /// </summary>
        internal static string RequiredAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RequiredAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error dispatching on controller {0}, conflicting actions matched: {1}. 的本地化字符串。
        /// </summary>
        internal static string ResourceControllerFactory_ConflictingActions {
            get {
                return ResourceManager.GetString("ResourceControllerFactory_ConflictingActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error dispatching on controller {0}, no actions matched. 的本地化字符串。
        /// </summary>
        internal static string ResourceControllerFactory_NoActions {
            get {
                return ResourceManager.GetString("ResourceControllerFactory_NoActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Format &apos;{0}&apos; is not supported. 的本地化字符串。
        /// </summary>
        internal static string Resources_UnsupportedFormat {
            get {
                return ResourceManager.GetString("Resources_UnsupportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsupported Media Type: &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string Resources_UnsupportedMediaType {
            get {
                return ResourceManager.GetString("Resources_UnsupportedMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否需要自动创建SqlStruct结构 的本地化字符串。
        /// </summary>
        internal static string SqlStruct_AutoGeneration {
            get {
                return ResourceManager.GetString("SqlStruct_AutoGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置要对数据源执行的 Transact-SQL 语句、表名或存储过程。 的本地化字符串。
        /// </summary>
        internal static string SqlStruct_CommandText {
            get {
                return ResourceManager.GetString("SqlStruct_CommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置在终止执行命令的尝试并生成错误之前的等待时间 的本地化字符串。
        /// </summary>
        internal static string SqlStruct_CommandTimeout {
            get {
                return ResourceManager.GetString("SqlStruct_CommandTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，该值指示如何解释 CommandText 属性。 的本地化字符串。
        /// </summary>
        internal static string SqlStruct_CommandType {
            get {
                return ResourceManager.GetString("SqlStruct_CommandType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前数据库连接类型 的本地化字符串。
        /// </summary>
        internal static string SqlStruct_ConnectionType {
            get {
                return ResourceManager.GetString("SqlStruct_ConnectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置当前Transact-SQL命令是否制定动态参数,指执行Transact-SQL 语句时根据传入参数动态制定SQL语句的参数。 的本地化字符串。
        /// </summary>
        internal static string SqlStruct_DynamicParameter {
            get {
                return ResourceManager.GetString("SqlStruct_DynamicParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DbCommand命令执行参数集合 的本地化字符串。
        /// </summary>
        internal static string SqlStruct_Parameters {
            get {
                return ResourceManager.GetString("SqlStruct_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果 Transact-SQL语句返回单值，则需要进行的迭代字段名称 的本地化字符串。
        /// </summary>
        internal static string SqlStruct_ReturnColumn {
            get {
                return ResourceManager.GetString("SqlStruct_ReturnColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前命令结构是否需要进行连接参数转换 的本地化字符串。
        /// </summary>
        internal static string SqlStruct_TransferParameter {
            get {
                return ResourceManager.GetString("SqlStruct_TransferParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Xml文件中此结构的元素名称 的本地化字符串。
        /// </summary>
        internal static string SqlStruct_XmlElementName {
            get {
                return ResourceManager.GetString("SqlStruct_XmlElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DbCommand命令结构列表 的本地化字符串。
        /// </summary>
        internal static string SqlStructXmlClass_SqlStructs {
            get {
                return ResourceManager.GetString("SqlStructXmlClass_SqlStructs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库表列信息 的本地化字符串。
        /// </summary>
        internal static string SqlStructXmlClass_TableColumns {
            get {
                return ResourceManager.GetString("SqlStructXmlClass_TableColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库视图名称 的本地化字符串。
        /// </summary>
        internal static string SqlStructXmlClass_TableName {
            get {
                return ResourceManager.GetString("SqlStructXmlClass_TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库表名称 的本地化字符串。
        /// </summary>
        internal static string SqlStructXmlClass_ViewName {
            get {
                return ResourceManager.GetString("SqlStructXmlClass_ViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前窗口已经执行完新增操作 的本地化字符串。
        /// </summary>
        internal static string StatusModeEnum_AddNewed {
            get {
                return ResourceManager.GetString("StatusModeEnum_AddNewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前窗口正在执行新增操作，一般为开始新增后标记 的本地化字符串。
        /// </summary>
        internal static string StatusModeEnum_AddNewing {
            get {
                return ResourceManager.GetString("StatusModeEnum_AddNewing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前窗口已经执行完取消操作。 的本地化字符串。
        /// </summary>
        internal static string StatusModeEnum_Canceled {
            get {
                return ResourceManager.GetString("StatusModeEnum_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前窗口正在执行取消操作，一般为开始取消后标记。 的本地化字符串。
        /// </summary>
        internal static string StatusModeEnum_Canceling {
            get {
                return ResourceManager.GetString("StatusModeEnum_Canceling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前窗口已经执行完确认操作。 的本地化字符串。
        /// </summary>
        internal static string StatusModeEnum_Confirmed {
            get {
                return ResourceManager.GetString("StatusModeEnum_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前窗口正在执行确认操作，一般为开始确认后标记。 的本地化字符串。
        /// </summary>
        internal static string StatusModeEnum_Confirming {
            get {
                return ResourceManager.GetString("StatusModeEnum_Confirming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前窗口已经执行完删除操作。 的本地化字符串。
        /// </summary>
        internal static string StatusModeEnum_Deleted {
            get {
                return ResourceManager.GetString("StatusModeEnum_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前窗口正在执行删除操作，一般为开始删除后标记。 的本地化字符串。
        /// </summary>
        internal static string StatusModeEnum_Deleting {
            get {
                return ResourceManager.GetString("StatusModeEnum_Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述页面的各种操作状态 的本地化字符串。
        /// </summary>
        internal static string StatusModeEnum_Description {
            get {
                return ResourceManager.GetString("StatusModeEnum_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前窗口已经执行完导出操作。 的本地化字符串。
        /// </summary>
        internal static string StatusModeEnum_Exported {
            get {
                return ResourceManager.GetString("StatusModeEnum_Exported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前窗口正在执行导出操作，一般为开始导出增后标记。 的本地化字符串。
        /// </summary>
        internal static string StatusModeEnum_Exporting {
            get {
                return ResourceManager.GetString("StatusModeEnum_Exporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前窗口已经执行完导入操作。 的本地化字符串。
        /// </summary>
        internal static string StatusModeEnum_Imported {
            get {
                return ResourceManager.GetString("StatusModeEnum_Imported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前窗口正在执行导入操作，一般为开始导入后标记。 的本地化字符串。
        /// </summary>
        internal static string StatusModeEnum_Importing {
            get {
                return ResourceManager.GetString("StatusModeEnum_Importing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前页面无任何状态，一般指刚刚进入页面还没进行任何操作。 的本地化字符串。
        /// </summary>
        internal static string StatusModeEnum_None {
            get {
                return ResourceManager.GetString("StatusModeEnum_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前窗口已经执行保存增操作。 的本地化字符串。
        /// </summary>
        internal static string StatusModeEnum_Saved {
            get {
                return ResourceManager.GetString("StatusModeEnum_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前窗口正在执行保存操作，一般为开始保存后标记。 的本地化字符串。
        /// </summary>
        internal static string StatusModeEnum_Saving {
            get {
                return ResourceManager.GetString("StatusModeEnum_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前窗口已经执行完查询操作。 的本地化字符串。
        /// </summary>
        internal static string StatusModeEnum_Searched {
            get {
                return ResourceManager.GetString("StatusModeEnum_Searched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前窗口正在执行查询操作，一般为开始查询后标记。 的本地化字符串。
        /// </summary>
        internal static string StatusModeEnum_Searching {
            get {
                return ResourceManager.GetString("StatusModeEnum_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前窗口已经执行完未知操作。 的本地化字符串。
        /// </summary>
        internal static string StatusModeEnum_UnkwonOperated {
            get {
                return ResourceManager.GetString("StatusModeEnum_UnkwonOperated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前窗口正在执行未知操作，一般为开始未知操作后标记 的本地化字符串。
        /// </summary>
        internal static string StatusModeEnum_UnkwonOperating {
            get {
                return ResourceManager.GetString("StatusModeEnum_UnkwonOperating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前窗口已经执行完更新操作。 的本地化字符串。
        /// </summary>
        internal static string StatusModeEnum_Updated {
            get {
                return ResourceManager.GetString("StatusModeEnum_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前窗口正在执行更新操作，一般为开始更新后标记。 的本地化字符串。
        /// </summary>
        internal static string StatusModeEnum_Updating {
            get {
                return ResourceManager.GetString("StatusModeEnum_Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件{0}不存在，请检查路径或文件名是否正确!	 的本地化字符串。
        /// </summary>
        internal static string StructBuilder_NotExistFile {
            get {
                return ResourceManager.GetString("StructBuilder_NotExistFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指示当前存在可被提交的事务，且事务允许被提交。 的本地化字符串。
        /// </summary>
        internal static string TransactionState_AllowCommitTransaction {
            get {
                return ResourceManager.GetString("TransactionState_AllowCommitTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指示当前存在可被回滚的事务，且事务允许被回滚。 的本地化字符串。
        /// </summary>
        internal static string TransactionState_AllowRollbackTransaction {
            get {
                return ResourceManager.GetString("TransactionState_AllowRollbackTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指示当前存在可被提交的事务，且事务已经被提交，如果在提交则系统抛出TransactionInDoubtException异常。 的本地化字符串。
        /// </summary>
        internal static string TransactionState_AlreadyCommitTransaction {
            get {
                return ResourceManager.GetString("TransactionState_AlreadyCommitTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指示当前存在可被提交的事务，且事务已经被回滚，如果在提交则系统抛出TransactionInDoubtException异常。 的本地化字符串。
        /// </summary>
        internal static string TransactionState_AlreadyRollbackTransaction {
            get {
                return ResourceManager.GetString("TransactionState_AlreadyRollbackTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事务的提交状态枚举。 的本地化字符串。
        /// </summary>
        internal static string TransactionState_Description {
            get {
                return ResourceManager.GetString("TransactionState_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指示当前存在可被提交的事务。 的本地化字符串。
        /// </summary>
        internal static string TransactionState_ExistTransaction {
            get {
                return ResourceManager.GetString("TransactionState_ExistTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指示当前不存在可被提交的事务。 的本地化字符串。
        /// </summary>
        internal static string TransactionState_NotExistTransaction {
            get {
                return ResourceManager.GetString("TransactionState_NotExistTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未能找到名为 {0} 的属性。 的本地化字符串。
        /// </summary>
        internal static string UnknownProperty {
            get {
                return ResourceManager.GetString("UnknownProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} field is not a valid fully-qualified http, https, or ftp URL. 的本地化字符串。
        /// </summary>
        internal static string UrlAttribute_Invalid {
            get {
                return ResourceManager.GetString("UrlAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} field is not a valid URL. 的本地化字符串。
        /// </summary>
        internal static string UrlAttributeProtocolOptional_Invalid {
            get {
                return ResourceManager.GetString("UrlAttributeProtocolOptional_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} field is not a valid protocol-less URL. 的本地化字符串。
        /// </summary>
        internal static string UrlAttributeWithoutProtocol_Invalid {
            get {
                return ResourceManager.GetString("UrlAttributeWithoutProtocol_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 instance 必须匹配 ValidationContext 提供的实例 ObjectInstance。 的本地化字符串。
        /// </summary>
        internal static string Validator_InstanceMustMatchValidationContextInstance {
            get {
                return ResourceManager.GetString("Validator_InstanceMustMatchValidationContextInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作:{0}
        ///消息:{1}
        ///计算机:{2}
        ///用户:{3} 的本地化字符串。
        /// </summary>
        internal static string WindowsStorage_ActionMessage {
            get {
                return ResourceManager.GetString("WindowsStorage_ActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 金软科技 的本地化字符串。
        /// </summary>
        internal static string WindowsStorage_EventSource {
            get {
                return ResourceManager.GetString("WindowsStorage_EventSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常信息:{0}
        ///异常源:{1}
        ///异常栈:{2} 的本地化字符串。
        /// </summary>
        internal static string WindowsStorage_Exception {
            get {
                return ResourceManager.GetString("WindowsStorage_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作:{0}
        ///消息:{1}
        ///计算机:{2}
        ///用户:{3}
        ///异常信息:{4}
        ///异常源:{5}
        ///异常栈:{6} 的本地化字符串。
        /// </summary>
        internal static string WindowsStorage_ExceptionMessage {
            get {
                return ResourceManager.GetString("WindowsStorage_ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前方法{0}在{1}类中不可用。 的本地化字符串。
        /// </summary>
        internal static string WindowsStorage_UselessMethod {
            get {
                return ResourceManager.GetString("WindowsStorage_UselessMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} field is not a valid year 的本地化字符串。
        /// </summary>
        internal static string YearAttribute_Invalid {
            get {
                return ResourceManager.GetString("YearAttribute_Invalid", resourceCulture);
            }
        }
    }
}
