//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basic.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DesignerStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DesignerStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Basic.Properties.DesignerStrings", typeof(DesignerStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _5000 {
            get {
                object obj = ResourceManager.GetObject("5000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _5001 {
            get {
                object obj = ResourceManager.GetObject("5001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _5002 {
            get {
                object obj = ResourceManager.GetObject("5002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _5003 {
            get {
                object obj = ResourceManager.GetObject("5003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _5004 {
            get {
                object obj = ResourceManager.GetObject("5004", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _5005 {
            get {
                object obj = ResourceManager.GetObject("5005", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _5006 {
            get {
                object obj = ResourceManager.GetObject("5006", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _5007 {
            get {
                object obj = ResourceManager.GetObject("5007", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Arguments 的本地化字符串。
        /// </summary>
        internal static string DataCommand_Arguments {
            get {
                return ResourceManager.GetString("DataCommand_Arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CheckCommands 的本地化字符串。
        /// </summary>
        internal static string DataCommand_CheckCommands {
            get {
                return ResourceManager.GetString("DataCommand_CheckCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NewCommands 的本地化字符串。
        /// </summary>
        internal static string DataCommand_NewCommands {
            get {
                return ResourceManager.GetString("DataCommand_NewCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameters 的本地化字符串。
        /// </summary>
        internal static string DataCommand_Parameters {
            get {
                return ResourceManager.GetString("DataCommand_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Properties 的本地化字符串。
        /// </summary>
        internal static string DataCommand_Properties {
            get {
                return ResourceManager.GetString("DataCommand_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性特性 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_Attributes {
            get {
                return ResourceManager.GetString("PersistentCategory_Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测命令 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_CheckCommands {
            get {
                return ResourceManager.GetString("PersistentCategory_CheckCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码生成 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_CodeGenerator {
            get {
                return ResourceManager.GetString("PersistentCategory_CodeGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据集合列表 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_Collections {
            get {
                return ResourceManager.GetString("PersistentCategory_Collections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段信息 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_Column {
            get {
                return ResourceManager.GetString("PersistentCategory_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_Content {
            get {
                return ResourceManager.GetString("PersistentCategory_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据命令 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_DataCommand {
            get {
                return ResourceManager.GetString("PersistentCategory_DataCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询条件类 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_DataCondition {
            get {
                return ResourceManager.GetString("PersistentCategory_DataCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据协定 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_DataContract {
            get {
                return ResourceManager.GetString("PersistentCategory_DataContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示格式 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_Display {
            get {
                return ResourceManager.GetString("PersistentCategory_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动态命令 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_DynamicCommand {
            get {
                return ResourceManager.GetString("PersistentCategory_DynamicCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新值命令 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_NewCommands {
            get {
                return ResourceManager.GetString("PersistentCategory_NewCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令参数 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_Parameter {
            get {
                return ResourceManager.GetString("PersistentCategory_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_Property {
            get {
                return ResourceManager.GetString("PersistentCategory_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调用参数类型。 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_ArgumentsType {
            get {
                return ResourceManager.GetString("PersistentDescription_ArgumentsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置当前数据持久类需要继承的基类类型。 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_BaseAccess {
            get {
                return ResourceManager.GetString("PersistentDescription_BaseAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个 String 值，该值指示当前实体类的基类类型。 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_BaseClass {
            get {
                return ResourceManager.GetString("PersistentDescription_BaseClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测实体属性是否允许执行此命令，检测通过则允许执行，否则返回异常信息。 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_CheckCommand {
            get {
                return ResourceManager.GetString("PersistentDescription_CheckCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，该值指示实体模型的类名称。 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_ClassName {
            get {
                return ResourceManager.GetString("PersistentDescription_ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，该值指示字段是否为计算列 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_ColumnComputed {
            get {
                return ResourceManager.GetString("PersistentDescription_ColumnComputed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置数据库字段的 DbType。 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_ColumnDbType {
            get {
                return ResourceManager.GetString("PersistentDescription_ColumnDbType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，该值指示实体属性所对应的字段名称 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_ColumnName {
            get {
                return ResourceManager.GetString("PersistentDescription_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置列中数据的最大大小（以字节为单位） 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_ColumnPrecision {
            get {
                return ResourceManager.GetString("PersistentDescription_ColumnPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，该值指示字段是否为数据库表主键 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_ColumnPrimaryKey {
            get {
                return ResourceManager.GetString("PersistentDescription_ColumnPrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，该值指示字段所属表的别名 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_ColumnProfix {
            get {
                return ResourceManager.GetString("PersistentDescription_ColumnProfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取数据库表中列集合 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_Columns {
            get {
                return ResourceManager.GetString("PersistentDescription_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置数据库参数值解析为的小数位数 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_ColumnScale {
            get {
                return ResourceManager.GetString("PersistentDescription_ColumnScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置列中数据的最大大小（以字节为单位） 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_ColumnSize {
            get {
                return ResourceManager.GetString("PersistentDescription_ColumnSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置要对数据源执行的 Transact-SQL 语句、表名或存储过程 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_CommandText {
            get {
                return ResourceManager.GetString("PersistentDescription_CommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 &quot;{0}&quot; 属性 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_CommandText_Editor {
            get {
                return ResourceManager.GetString("PersistentDescription_CommandText_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性描述 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_Comment {
            get {
                return ResourceManager.GetString("PersistentDescription_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前命令执行时需要传入的条件类实例。 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_DataConditionProperties {
            get {
                return ResourceManager.GetString("PersistentDescription_DataConditionProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示当前对象是否需要使用数据契约。 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_DataContract {
            get {
                return ResourceManager.GetString("PersistentDescription_DataContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置类型是否使用数据协定。 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_DataContract_Generate {
            get {
                return ResourceManager.GetString("PersistentDescription_DataContract_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，该值指示是否保留对象引用数据。 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_DataContract_IsReference {
            get {
                return ResourceManager.GetString("PersistentDescription_DataContract_IsReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置类型的数据协定的名称。 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_DataContract_Name {
            get {
                return ResourceManager.GetString("PersistentDescription_DataContract_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置类型的数据协定的命名空间。 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_DataContract_Namespace {
            get {
                return ResourceManager.GetString("PersistentDescription_DataContract_Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置当前数据持久类的描述信息 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_Description {
            get {
                return ResourceManager.GetString("PersistentDescription_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体类文件所在的项目文件夹 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_EntityFolder {
            get {
                return ResourceManager.GetString("PersistentDescription_EntityFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置当前数据持久类，数据实体类的名称 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_EntityName {
            get {
                return ResourceManager.GetString("PersistentDescription_EntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体文件所在项目 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_EntityProject {
            get {
                return ResourceManager.GetString("PersistentDescription_EntityProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体类初始化操作类型，默认为生成多个实体类。 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_Generate {
            get {
                return ResourceManager.GetString("PersistentDescription_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置实体类生成方式，包含生成实体类，生成强类型DataTable，生成实体类和强类型DataTable。 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_GeneratorMode {
            get {
                return ResourceManager.GetString("PersistentDescription_GeneratorMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置资源组的名称 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_GroupName {
            get {
                return ResourceManager.GetString("PersistentDescription_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get or set Resource&apos;s Group 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_GroupName_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_GroupName-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，该值指示当前实体是否生成首抽象类 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_IsAbstract {
            get {
                return ResourceManager.GetString("PersistentDescription_IsAbstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，该值指示当前实体是否生成首抽象类 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_IsAbstract_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_IsAbstract-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源本地化转换器名称 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_MessageConverter {
            get {
                return ResourceManager.GetString("PersistentDescription_MessageConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Converter Name of localization resource 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_MessageConverter_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_MessageConverter-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置实体类的访问修饰符 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_Modifier {
            get {
                return ResourceManager.GetString("PersistentDescription_Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置实体类的访问修饰符 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_Modifier_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_Modifier-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从数据库中创建实体属性的新值。 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_NewCommand {
            get {
                return ResourceManager.GetString("PersistentDescription_NewCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从数据库中创建实体属性的新值。 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_NewCommand_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_NewCommand-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示 DbCommand 的参数，也可以是它到 DataSet/DataTable 列的映射。 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_Parameter {
            get {
                return ResourceManager.GetString("PersistentDescription_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示 DbCommand 的参数，也可以是它到 DataSet/DataTable 列的映射。 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_Parameter_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_Parameter-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示与 DbCommand 相关联的参数的集合以及各个参数到 DataSet/DataTable 中列的映射。 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_ParameterCollection {
            get {
                return ResourceManager.GetString("PersistentDescription_ParameterCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示与 DbCommand 相关联的参数的集合以及各个参数到 DataSet/DataTable 中列的映射。 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_ParameterCollection_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_ParameterCollection-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体属性的描述 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_PropertyComment {
            get {
                return ResourceManager.GetString("PersistentDescription_PropertyComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comment for Property of entity  的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_PropertyComment_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_PropertyComment-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，该值指示当前属性是否需要添加标记System.Runtime.Serialization.DataMemberAttribute 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_PropertyDataMember {
            get {
                return ResourceManager.GetString("PersistentDescription_PropertyDataMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，该值指示当前属性是否需要添加标记System.Runtime.Serialization.DataMemberAttribute 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_PropertyDataMember_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_PropertyDataMember-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否为继承属性，如果是继承属性，则在当前类实例中不写入属性信息。 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_PropertyInheritance {
            get {
                return ResourceManager.GetString("PersistentDescription_PropertyInheritance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is inheritance property. 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_PropertyInheritance_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_PropertyInheritance-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，表示实体类中属性的名称 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_PropertyName {
            get {
                return ResourceManager.GetString("PersistentDescription_PropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the name of the dataentity&apos;s property 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_PropertyName_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_PropertyName-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，该值指示实体属性是否接受空值 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_PropertyNullable {
            get {
                return ResourceManager.GetString("PersistentDescription_PropertyNullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets a value that indicates whether the property accepts null values 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_PropertyNullable_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_PropertyNullable-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个布尔值，该值指示是否需要重载基类属性。 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_PropertyOverride {
            get {
                return ResourceManager.GetString("PersistentDescription_PropertyOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get or set a Boolean value, the value indicating whether to override a base class property. 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_PropertyOverride_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_PropertyOverride-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，表示实体类中属性的类型 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_PropertyType {
            get {
                return ResourceManager.GetString("PersistentDescription_PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the type of the dataentity&apos;s property 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_PropertyType_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_PropertyType-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个布尔值，该值指示是否虚拟属性。 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_PropertyVirtual {
            get {
                return ResourceManager.GetString("PersistentDescription_PropertyVirtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get or set a Boolean value, the value indicating whether the virtual property. 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_PropertyVirtual_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_PropertyVirtual-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取当前数据持久类对应的数据表信息 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_TableInfo {
            get {
                return ResourceManager.GetString("PersistentDescription_TableInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取当前数据持久类对应的数据表信息 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_TableInfo_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_TableInfo-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取当前数据持久类的表名称 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_TableName {
            get {
                return ResourceManager.GetString("PersistentDescription_TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取当前数据持久类的表名称 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_TableName_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_TableName-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置当前数据持久类的视图名称 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_ViewName {
            get {
                return ResourceManager.GetString("PersistentDescription_ViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置当前数据持久类的视图名称 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_ViewName_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_ViewName-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定数据连接 的本地化字符串。
        /// </summary>
        internal static string PersistentDisplay_ApplyConnection {
            get {
                return ResourceManager.GetString("PersistentDisplay_ApplyConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection 的本地化字符串。
        /// </summary>
        internal static string PersistentDisplay_ApplyConnection_en_US {
            get {
                return ResourceManager.GetString("PersistentDisplay_ApplyConnection-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据列集合 的本地化字符串。
        /// </summary>
        internal static string PersistentDisplay_Columns {
            get {
                return ResourceManager.GetString("PersistentDisplay_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Columns 的本地化字符串。
        /// </summary>
        internal static string PersistentDisplay_Columns_en_US {
            get {
                return ResourceManager.GetString("PersistentDisplay_Columns-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 持久类描述 的本地化字符串。
        /// </summary>
        internal static string PersistentDisplay_Description {
            get {
                return ResourceManager.GetString("PersistentDisplay_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Persistent Description 的本地化字符串。
        /// </summary>
        internal static string PersistentDisplay_Description_en_US {
            get {
                return ResourceManager.GetString("PersistentDisplay_Description-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体文件夹 的本地化字符串。
        /// </summary>
        internal static string PersistentDisplay_EntityFolder {
            get {
                return ResourceManager.GetString("PersistentDisplay_EntityFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Folder Of Entity Class  的本地化字符串。
        /// </summary>
        internal static string PersistentDisplay_EntityFolder_en_US {
            get {
                return ResourceManager.GetString("PersistentDisplay_EntityFolder-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体模型名称 的本地化字符串。
        /// </summary>
        internal static string PersistentDisplay_EntityName {
            get {
                return ResourceManager.GetString("PersistentDisplay_EntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entity Model Name 的本地化字符串。
        /// </summary>
        internal static string PersistentDisplay_EntityName_en_US {
            get {
                return ResourceManager.GetString("PersistentDisplay_EntityName-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据实体类命名空间 的本地化字符串。
        /// </summary>
        internal static string PersistentDisplay_EntityNamespace {
            get {
                return ResourceManager.GetString("PersistentDisplay_EntityNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Namespace Of Data Entity Class 的本地化字符串。
        /// </summary>
        internal static string PersistentDisplay_EntityNamespace_en_US {
            get {
                return ResourceManager.GetString("PersistentDisplay_EntityNamespace-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体文件项目 的本地化字符串。
        /// </summary>
        internal static string PersistentDisplay_EntityProject {
            get {
                return ResourceManager.GetString("PersistentDisplay_EntityProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Of Entity Class  的本地化字符串。
        /// </summary>
        internal static string PersistentDisplay_EntityProject_en_US {
            get {
                return ResourceManager.GetString("PersistentDisplay_EntityProject-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源组名称 的本地化字符串。
        /// </summary>
        internal static string PersistentDisplay_GroupName {
            get {
                return ResourceManager.GetString("PersistentDisplay_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resource&apos;s Group 的本地化字符串。
        /// </summary>
        internal static string PersistentDisplay_GroupName_en_US {
            get {
                return ResourceManager.GetString("PersistentDisplay_GroupName-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换器名称 的本地化字符串。
        /// </summary>
        internal static string PersistentDisplay_MessageConverter {
            get {
                return ResourceManager.GetString("PersistentDisplay_MessageConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Converter Name 的本地化字符串。
        /// </summary>
        internal static string PersistentDisplay_MessageConverter_en_US {
            get {
                return ResourceManager.GetString("PersistentDisplay_MessageConverter-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据持久类命名空间 的本地化字符串。
        /// </summary>
        internal static string PersistentDisplay_Namespace {
            get {
                return ResourceManager.GetString("PersistentDisplay_Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Namespace Of Data Persistent Class 的本地化字符串。
        /// </summary>
        internal static string PersistentDisplay_Namespace_en_US {
            get {
                return ResourceManager.GetString("PersistentDisplay_Namespace-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据表名称 的本地化字符串。
        /// </summary>
        internal static string PersistentDisplay_TableName {
            get {
                return ResourceManager.GetString("PersistentDisplay_TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Table Name 的本地化字符串。
        /// </summary>
        internal static string PersistentDisplay_TableName_en_US {
            get {
                return ResourceManager.GetString("PersistentDisplay_TableName-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视图名称 的本地化字符串。
        /// </summary>
        internal static string PersistentDisplay_ViewName {
            get {
                return ResourceManager.GetString("PersistentDisplay_ViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View Name 的本地化字符串。
        /// </summary>
        internal static string PersistentDisplay_ViewName_en_US {
            get {
                return ResourceManager.GetString("PersistentDisplay_ViewName-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前数据库上下文类是否指定连接，如果为true则继承于AbstractContext类或AbstractDataContext类，否则继承于AbstractTableContext类或AbstractDataContext类 的本地化字符串。
        /// </summary>
        internal static string PersistentGenerator_ApplyConnection {
            get {
                return ResourceManager.GetString("PersistentGenerator_ApplyConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whether the current database context class specifies the connection, if it is true the inherited from AbstractContext class or AbstractDataContext class, class inheritance in AbstractTableContext or AbstractDataContext otherwise 的本地化字符串。
        /// </summary>
        internal static string PersistentGenerator_ApplyConnection_en_US {
            get {
                return ResourceManager.GetString("PersistentGenerator_ApplyConnection-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置当前数据持久类需要继承的基类类型。 的本地化字符串。
        /// </summary>
        internal static string PersistentGenerator_BaseAccess {
            get {
                return ResourceManager.GetString("PersistentGenerator_BaseAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置当前数据持久类需要继承的基类类型。 的本地化字符串。
        /// </summary>
        internal static string PersistentGenerator_BaseAccess_en_US {
            get {
                return ResourceManager.GetString("PersistentGenerator_BaseAccess-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前数据持久类是否需要生成 ORACLE 配置文件，默认为不生成。 的本地化字符串。
        /// </summary>
        internal static string PersistentGenerator_BuildOraf {
            get {
                return ResourceManager.GetString("PersistentGenerator_BuildOraf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成ORACLE配置文件 的本地化字符串。
        /// </summary>
        internal static string PersistentGenerator_BuildOraf_Display {
            get {
                return ResourceManager.GetString("PersistentGenerator_BuildOraf_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Build Oracle Configuration File 的本地化字符串。
        /// </summary>
        internal static string PersistentGenerator_BuildOraf_Display_en_US {
            get {
                return ResourceManager.GetString("PersistentGenerator_BuildOraf_Display-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前数据持久类是否需要生成 ORACLE 配置文件，默认为不生成。 的本地化字符串。
        /// </summary>
        internal static string PersistentGenerator_BuildOraf_en_US {
            get {
                return ResourceManager.GetString("PersistentGenerator_BuildOraf-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前数据持久类是否需要生成 SQL SERVER 配置文件，默认为生成。 的本地化字符串。
        /// </summary>
        internal static string PersistentGenerator_BuildSqlf {
            get {
                return ResourceManager.GetString("PersistentGenerator_BuildSqlf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成SQL SERVER配置文件 的本地化字符串。
        /// </summary>
        internal static string PersistentGenerator_BuildSqlf_Display {
            get {
                return ResourceManager.GetString("PersistentGenerator_BuildSqlf_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Build SQL SERVER Configuration File 的本地化字符串。
        /// </summary>
        internal static string PersistentGenerator_BuildSqlf_Display_en_US {
            get {
                return ResourceManager.GetString("PersistentGenerator_BuildSqlf_Display-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前数据持久类是否需要生成 SQL SERVER 配置文件，默认为生成。 的本地化字符串。
        /// </summary>
        internal static string PersistentGenerator_BuildSqlf_en_US {
            get {
                return ResourceManager.GetString("PersistentGenerator_BuildSqlf-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示当前数据持久类中关于生成代码部分的说明 的本地化字符串。
        /// </summary>
        internal static string PersistentGenerator_Description {
            get {
                return ResourceManager.GetString("PersistentGenerator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 about information for data persistent class&apos;generator. 的本地化字符串。
        /// </summary>
        internal static string PersistentGenerator_Description_en_US {
            get {
                return ResourceManager.GetString("PersistentGenerator_Description-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前数据持久类是否需要生成持久类上下文管理类 的本地化字符串。
        /// </summary>
        internal static string PersistentGenerator_GenerateContext {
            get {
                return ResourceManager.GetString("PersistentGenerator_GenerateContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前数据持久类是否需要生成持久类上下文管理类 的本地化字符串。
        /// </summary>
        internal static string PersistentGenerator_GenerateContext_en_US {
            get {
                return ResourceManager.GetString("PersistentGenerator_GenerateContext-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体类初始化操作类型，默认为生成多个实体类。 的本地化字符串。
        /// </summary>
        internal static string PersistentGenerator_GenerateMode {
            get {
                return ResourceManager.GetString("PersistentGenerator_GenerateMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体类初始化操作类型，默认为生成多个实体类。 的本地化字符串。
        /// </summary>
        internal static string PersistentGenerator_GenerateMode_en_US {
            get {
                return ResourceManager.GetString("PersistentGenerator_GenerateMode-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置实体类的访问修饰符 的本地化字符串。
        /// </summary>
        internal static string PersistentGenerator_Modifier {
            get {
                return ResourceManager.GetString("PersistentGenerator_Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置实体类的访问修饰符 的本地化字符串。
        /// </summary>
        internal static string PersistentGenerator_Modifier_en_US {
            get {
                return ResourceManager.GetString("PersistentGenerator_Modifier-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置数据持久类需要支持的数据库类型 的本地化字符串。
        /// </summary>
        internal static string PersistentGenerator_SupportDatabases {
            get {
                return ResourceManager.GetString("PersistentGenerator_SupportDatabases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 支持的数据库 的本地化字符串。
        /// </summary>
        internal static string PersistentGenerator_SupportDatabases_Display {
            get {
                return ResourceManager.GetString("PersistentGenerator_SupportDatabases_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Support Databases 的本地化字符串。
        /// </summary>
        internal static string PersistentGenerator_SupportDatabases_Display_en_US {
            get {
                return ResourceManager.GetString("PersistentGenerator_SupportDatabases_Display-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get or set the data persistent class needs to support the database type 的本地化字符串。
        /// </summary>
        internal static string PersistentGenerator_SupportDatabases_en_US {
            get {
                return ResourceManager.GetString("PersistentGenerator_SupportDatabases-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CodeGenerator 的本地化字符串。
        /// </summary>
        internal static string PropertyCategory_CodeGenerator {
            get {
                return ResourceManager.GetString("PropertyCategory_CodeGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content 的本地化字符串。
        /// </summary>
        internal static string PropertyCategory_Content {
            get {
                return ResourceManager.GetString("PropertyCategory_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DataCommand 的本地化字符串。
        /// </summary>
        internal static string PropertyCategory_DataCommand {
            get {
                return ResourceManager.GetString("PropertyCategory_DataCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示验证特性集合 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_Attributes {
            get {
                return ResourceManager.GetString("PropertyDescription_Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示验证特性集合 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_Attributes_en_US {
            get {
                return ResourceManager.GetString("PropertyDescription_Attributes-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定布尔类型的属性显示可选文本的定义 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_BooleanDisplay {
            get {
                return ResourceManager.GetString("PropertyDescription_BooleanDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定布尔类型的属性显示可选文本的定义 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_BooleanDisplay_en_US {
            get {
                return ResourceManager.GetString("PropertyDescription_BooleanDisplay-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示条件模型生成器信息 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_DataConditionGenerator {
            get {
                return ResourceManager.GetString("PropertyDescription_DataConditionGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示条件模型生成器信息 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_DataConditionGenerator_en_US {
            get {
                return ResourceManager.GetString("PropertyDescription_DataConditionGenerator-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示实体模型生成器信息 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_DataEntityGenerator {
            get {
                return ResourceManager.GetString("PropertyDescription_DataEntityGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示实体模型生成器信息 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_DataEntityGenerator_en_US {
            get {
                return ResourceManager.GetString("PropertyDescription_DataEntityGenerator-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出格式 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_DataFormatString {
            get {
                return ResourceManager.GetString("PropertyDescription_DataFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output display format 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_DataFormatString_en_US {
            get {
                return ResourceManager.GetString("PropertyDescription_DataFormatString-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段类型 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_DbType {
            get {
                return ResourceManager.GetString("PropertyDescription_DbType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column Type 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_DbType_en_US {
            get {
                return ResourceManager.GetString("PropertyDescription_DbType-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置数据列的默认值。 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_DefaultValue {
            get {
                return ResourceManager.GetString("PropertyDescription_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the default value of column. 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_DefaultValue_en_US {
            get {
                return ResourceManager.GetString("PropertyDescription_DefaultValue-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，该值指示参数是只可输入、只可输出、双向还是存储过程返回值参数 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_Direction {
            get {
                return ResourceManager.GetString("PropertyDescription_Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets a value that indicates whether the parameter is input-only, output-only, bidirectional, or a stored procedure return value parameter 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_Direction_en_US {
            get {
                return ResourceManager.GetString("PropertyDescription_Direction-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定如何显示数据字段以及如何设置数据字段的格式 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_DisplayFormat {
            get {
                return ResourceManager.GetString("PropertyDescription_DisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specify how to display the data field and how to set the format of the data fields 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_DisplayFormat_en_US {
            get {
                return ResourceManager.GetString("PropertyDescription_DisplayFormat-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个允许空的布尔值，该值指示当前实体模型是否启用 IDataErrorInfo接口验证，如果设置值则覆盖AbstractEntity.GlobalEnabledValidation的设置。
        ///GlobalEnabledValidation的默认值为 False。 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_EnabledValidation {
            get {
                return ResourceManager.GetString("PropertyDescription_EnabledValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get or set a Boolean value for allowed to empty, the value indicating whether the this entity model enabled IDataErrorInfo&apos;s validation, if the setting values the cover AbstractEntity.GlobalEnabledValidation&apos;s value. GlobalEnabledValidation defaults to False. 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_EnabledValidation_en_US {
            get {
                return ResourceManager.GetString("PropertyDescription_EnabledValidation-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置当前数据持久类包含的实体类的命名空间 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_EntityNamespace {
            get {
                return ResourceManager.GetString("PropertyDescription_EntityNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets namespace of the data persistent class&apos;s entity 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_EntityNamespace_en_US {
            get {
                return ResourceManager.GetString("PropertyDescription_EntityNamespace-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，表示实体类型Guid。 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_Guid {
            get {
                return ResourceManager.GetString("PropertyDescription_Guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，表示实体类型Guid。 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_Guid_en_US {
            get {
                return ResourceManager.GetString("PropertyDescription_Guid-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，表示实体类名称 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_Name {
            get {
                return ResourceManager.GetString("PropertyDescription_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the name of the dataentity 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_Name_en_US {
            get {
                return ResourceManager.GetString("PropertyDescription_Name-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置当前数据持久类的命名空间 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_NameSpace {
            get {
                return ResourceManager.GetString("PropertyDescription_NameSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets namespace of the data persistent class 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_NameSpace_en_US {
            get {
                return ResourceManager.GetString("PropertyDescription_NameSpace-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，该值指示参数是否接受空值 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_Nullable {
            get {
                return ResourceManager.GetString("PropertyDescription_Nullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets a value that indicates whether the parameter accepts null values 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_Nullable_en_US {
            get {
                return ResourceManager.GetString("PropertyDescription_Nullable-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置 Parameter 的名称 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_ParameterName {
            get {
                return ResourceManager.GetString("PropertyDescription_ParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the name of the Parameter 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_ParameterName_en_US {
            get {
                return ResourceManager.GetString("PropertyDescription_ParameterName-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，该值指示参数数据库参数的类型 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_ParameterType {
            get {
                return ResourceManager.GetString("PropertyDescription_ParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the DbType of the parameter 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_ParameterType_en_US {
            get {
                return ResourceManager.GetString("PropertyDescription_ParameterType-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置列中数据的最大大小（以字节为单位） 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_Precision {
            get {
                return ResourceManager.GetString("PropertyDescription_Precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the maximum number of digits used to represent the Value property. 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_Precision_en_US {
            get {
                return ResourceManager.GetString("PropertyDescription_Precision-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_Property {
            get {
                return ResourceManager.GetString("PropertyDescription_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置数据库参数值解析为的小数位数 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_Scale {
            get {
                return ResourceManager.GetString("PropertyDescription_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置列中数据的最大大小（以字节为单位） 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_Size {
            get {
                return ResourceManager.GetString("PropertyDescription_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置源列的名称，该源列映射到 DataSet/Entity 并用于加载或返回 Value 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_SourceColumn {
            get {
                return ResourceManager.GetString("PropertyDescription_SourceColumn", resourceCulture);
            }
        }
    }
}
