<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="$(ProjectDir)..\..\packages\std-version.targets" />
	<PropertyGroup>
		<AssemblyName>Basic.DependencyInjections</AssemblyName>
		<RootNamespace>Basic</RootNamespace>
		<DelaySign>false</DelaySign>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PackageId>Standard.DependencyInjections</PackageId>
		<Product>Standard.DependencyInjections</Product>
		<PackageProjectUrl>https://gitee.com/terran-hero/basic</PackageProjectUrl>
		<PackageTags>ORM Linq Access Dependency Injections</PackageTags>
		<Authors>JACKY</Authors>
		<Description>ORM 框架依赖注入</Description>
		<Net6_0_Version>8.0.*</Net6_0_Version>
		<Net_Laster_Version>10.0.*</Net_Laster_Version>
	</PropertyGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net8.0' or '$(TargetFramework)' == 'net10.0'">
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="$(Net_Laster_Version)" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="$(Net_Laster_Version)" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="$(Net_Laster_Version)" />
		<PackageReference Include="System.Configuration.ConfigurationManager" Version="$(Net_Laster_Version)" />
		<PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="$(Net_Laster_Version)" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
		<PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="$(Net_Laster_Version)" />
		<PackageReference Include="System.Configuration.ConfigurationManager" Version="$(Net_Laster_Version)" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="$(Net_Laster_Version)" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="$(Net_Laster_Version)" />
		<PackageReference Include="System.Runtime.Caching" Version="$(Net_Laster_Version)" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net6.0'">
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="$(Net6_0_Version)" />
		<PackageReference Include="System.Configuration.ConfigurationManager" Version="$(Net6_0_Version)" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="$(Net6_0_Version)" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="$(Net6_0_Version)" />
		<PackageReference Include="System.Runtime.Caching" Version="$(Net6_0_Version)" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Standard.DataAccess\Standard.DataAccess.csproj" />
		<ProjectReference Include="..\Standard.EntityLayer\Standard.EntityLayer.csproj" />
	</ItemGroup>
	<Import Project="$(ProjectDir)..\..\packages\std-props.targets" />
</Project>