//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basic.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JsonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JsonStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Basic.Properties.JsonStrings", typeof(JsonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Type &apos;{0}&apos; is not supported for deserialization of an array. 的本地化字符串。
        /// </summary>
        internal static string JSON_ArrayTypeNotSupported {
            get {
                return ResourceManager.GetString("JSON_ArrayTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unrecognized escape sequence. 的本地化字符串。
        /// </summary>
        internal static string JSON_BadEscape {
            get {
                return ResourceManager.GetString("JSON_BadEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot convert object of type &apos;{0}&apos; to type &apos;{1}&apos; 的本地化字符串。
        /// </summary>
        internal static string JSON_CannotConvertObjectToType {
            get {
                return ResourceManager.GetString("JSON_CannotConvertObjectToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot create instance of {0}. 的本地化字符串。
        /// </summary>
        internal static string JSON_CannotCreateListType {
            get {
                return ResourceManager.GetString("JSON_CannotCreateListType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A circular reference was detected while serializing an object of type &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string JSON_CircularReference {
            get {
                return ResourceManager.GetString("JSON_CircularReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RecursionLimit exceeded. 的本地化字符串。
        /// </summary>
        internal static string JSON_DepthLimitExceeded {
            get {
                return ResourceManager.GetString("JSON_DepthLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot deserialize object graph into type of &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string JSON_DeserializerTypeMismatch {
            get {
                return ResourceManager.GetString("JSON_DeserializerTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type &apos;{0}&apos; is not supported for serialization/deserialization of a dictionary, keys must be strings or objects. 的本地化字符串。
        /// </summary>
        internal static string JSON_DictionaryTypeNotSupported {
            get {
                return ResourceManager.GetString("JSON_DictionaryTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid object passed in, &apos;{&apos; expected. 的本地化字符串。
        /// </summary>
        internal static string JSON_ExpectedOpenBrace {
            get {
                return ResourceManager.GetString("JSON_ExpectedOpenBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid JSON primitive: {0}. 的本地化字符串。
        /// </summary>
        internal static string JSON_IllegalPrimitive {
            get {
                return ResourceManager.GetString("JSON_IllegalPrimitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid array passed in, &apos;]&apos; expected. 的本地化字符串。
        /// </summary>
        internal static string JSON_InvalidArrayEnd {
            get {
                return ResourceManager.GetString("JSON_InvalidArrayEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid array passed in, &apos;,&apos; expected. 的本地化字符串。
        /// </summary>
        internal static string JSON_InvalidArrayExpectComma {
            get {
                return ResourceManager.GetString("JSON_InvalidArrayExpectComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid array passed in, extra trailing &apos;,&apos;. 的本地化字符串。
        /// </summary>
        internal static string JSON_InvalidArrayExtraComma {
            get {
                return ResourceManager.GetString("JSON_InvalidArrayExtraComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid array passed in, &apos;[&apos; expected. 的本地化字符串。
        /// </summary>
        internal static string JSON_InvalidArrayStart {
            get {
                return ResourceManager.GetString("JSON_InvalidArrayStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enums based on System.Int64 or System.UInt64 are not JSON-serializable because JavaScript does not support the necessary precision. 的本地化字符串。
        /// </summary>
        internal static string JSON_InvalidEnumType {
            get {
                return ResourceManager.GetString("JSON_InvalidEnumType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value must be a positive integer. 的本地化字符串。
        /// </summary>
        internal static string JSON_InvalidMaxJsonLength {
            get {
                return ResourceManager.GetString("JSON_InvalidMaxJsonLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid object passed in, member name expected. 的本地化字符串。
        /// </summary>
        internal static string JSON_InvalidMemberName {
            get {
                return ResourceManager.GetString("JSON_InvalidMemberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid object passed in, &apos;:&apos; or &apos;}&apos; expected. 的本地化字符串。
        /// </summary>
        internal static string JSON_InvalidObject {
            get {
                return ResourceManager.GetString("JSON_InvalidObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RecursionLimit must be a positive integer. 的本地化字符串。
        /// </summary>
        internal static string JSON_InvalidRecursionLimit {
            get {
                return ResourceManager.GetString("JSON_InvalidRecursionLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error during serialization or deserialization using the JSON JavaScriptSerializer. The length of the string exceeds the value set on the maxJsonLength property. 的本地化字符串。
        /// </summary>
        internal static string JSON_MaxJsonLengthExceeded {
            get {
                return ResourceManager.GetString("JSON_MaxJsonLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No parameterless constructor defined for type of &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string JSON_NoConstructor {
            get {
                return ResourceManager.GetString("JSON_NoConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid string passed in, &apos;\&quot;&apos; expected. 的本地化字符串。
        /// </summary>
        internal static string JSON_StringNotQuoted {
            get {
                return ResourceManager.GetString("JSON_StringNotQuoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unterminated string passed in. 的本地化字符串。
        /// </summary>
        internal static string JSON_UnterminatedString {
            get {
                return ResourceManager.GetString("JSON_UnterminatedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot convert null to a value type. 的本地化字符串。
        /// </summary>
        internal static string JSON_ValueTypeCannotBeNull {
            get {
                return ResourceManager.GetString("JSON_ValueTypeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; cannot be parsed as a unit as there are no numeric values in it. Examples of valid unit strings are &apos;1px&apos; and &apos;.5in&apos;. 的本地化字符串。
        /// </summary>
        internal static string UnitParseNoDigits {
            get {
                return ResourceManager.GetString("UnitParseNoDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The numeric part (&apos;{1}&apos;) of &apos;{0}&apos; cannot be parsed as a numeric part of a {2} unit. 的本地化字符串。
        /// </summary>
        internal static string UnitParseNumericPart {
            get {
                return ResourceManager.GetString("UnitParseNumericPart", resourceCulture);
            }
        }
    }
}
