//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basic.Localizations {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Basic.Localizations.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add... 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_AddCommand_en_US {
            get {
                return ResourceManager.GetString("BasicCommands_AddCommand-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加... 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_AddCommand_zh_CN {
            get {
                return ResourceManager.GetString("BasicCommands_AddCommand-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add a group 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_AddGroup_en_US {
            get {
                return ResourceManager.GetString("BasicCommands_AddGroup-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加分组依据 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_AddGroup_zh_CN {
            get {
                return ResourceManager.GetString("BasicCommands_AddGroup-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Relationship 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_AddRelation_en_US {
            get {
                return ResourceManager.GetString("BasicCommands_AddRelation-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加表关系 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_AddRelation_zh_CN {
            get {
                return ResourceManager.GetString("BasicCommands_AddRelation-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Table Objects 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_AddTable_en_US {
            get {
                return ResourceManager.GetString("BasicCommands_AddTable-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加表对象 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_AddTable_zh_CN {
            get {
                return ResourceManager.GetString("BasicCommands_AddTable-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bring Forward 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_BringForward_en_US {
            get {
                return ResourceManager.GetString("BasicCommands_BringForward-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上移一层 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_BringForward_zh_CN {
            get {
                return ResourceManager.GetString("BasicCommands_BringForward-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bring To Front 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_BringToFront_en_US {
            get {
                return ResourceManager.GetString("BasicCommands_BringToFront-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 置于顶层 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_BringToFront_zh_CN {
            get {
                return ResourceManager.GetString("BasicCommands_BringToFront-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Command 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_CreateCommand_en_US {
            get {
                return ResourceManager.GetString("BasicCommands_CreateCommand-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建命令 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_CreateCommand_zh_CN {
            get {
                return ResourceManager.GetString("BasicCommands_CreateCommand-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create localization resource 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_CreateResource_en_US {
            get {
                return ResourceManager.GetString("BasicCommands_CreateResource-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建本地化资源信息 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_CreateResource_zh_CN {
            get {
                return ResourceManager.GetString("BasicCommands_CreateResource-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Code 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_EditCode_en_US {
            get {
                return ResourceManager.GetString("BasicCommands_EditCode-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑代码 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_EditCode_zh_CN {
            get {
                return ResourceManager.GetString("BasicCommands_EditCode-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Command 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_EditCommand_en_US {
            get {
                return ResourceManager.GetString("BasicCommands_EditCommand-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改命令 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_EditCommand_zh_CN {
            get {
                return ResourceManager.GetString("BasicCommands_EditCommand-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initialize Table 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_InitializeTable_en_US {
            get {
                return ResourceManager.GetString("BasicCommands_InitializeTable-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化数据库表 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_InitializeTable_zh_CN {
            get {
                return ResourceManager.GetString("BasicCommands_InitializeTable-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Property 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_InsertProperty_en_US {
            get {
                return ResourceManager.GetString("BasicCommands_InsertProperty-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插入新属性 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_InsertProperty_zh_CN {
            get {
                return ResourceManager.GetString("BasicCommands_InsertProperty-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Property 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_NewProperty_en_US {
            get {
                return ResourceManager.GetString("BasicCommands_NewProperty-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加新属性 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_NewProperty_zh_CN {
            get {
                return ResourceManager.GetString("BasicCommands_NewProperty-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Order 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_OrderCommand_en_US {
            get {
                return ResourceManager.GetString("BasicCommands_OrderCommand-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顺序 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_OrderCommand_zh_CN {
            get {
                return ResourceManager.GetString("BasicCommands_OrderCommand-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste To Dynamic Command 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_PasteDynamicCommand_en_US {
            get {
                return ResourceManager.GetString("BasicCommands_PasteDynamicCommand-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粘帖为动态命令 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_PasteDynamicCommand_zh_CN {
            get {
                return ResourceManager.GetString("BasicCommands_PasteDynamicCommand-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste To Static Command 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_PasteStaticCommand_en_US {
            get {
                return ResourceManager.GetString("BasicCommands_PasteStaticCommand-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粘帖为静态命令 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_PasteStaticCommand_zh_CN {
            get {
                return ResourceManager.GetString("BasicCommands_PasteStaticCommand-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_Properties_en_US {
            get {
                return ResourceManager.GetString("BasicCommands_Properties-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_Properties_zh_CN {
            get {
                return ResourceManager.GetString("BasicCommands_Properties-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh Connection 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_RefreshConnection_en_US {
            get {
                return ResourceManager.GetString("BasicCommands_RefreshConnection-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置数据库连接 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_RefreshConnection_zh_CN {
            get {
                return ResourceManager.GetString("BasicCommands_RefreshConnection-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_Remove_en_US {
            get {
                return ResourceManager.GetString("BasicCommands_Remove-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_Remove_zh_CN {
            get {
                return ResourceManager.GetString("BasicCommands_Remove-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove a group 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_RemoveGroup_en_US {
            get {
                return ResourceManager.GetString("BasicCommands_RemoveGroup-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除分组依据 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_RemoveGroup_zh_CN {
            get {
                return ResourceManager.GetString("BasicCommands_RemoveGroup-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Resource Key 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_ResetResource_en_US {
            get {
                return ResourceManager.GetString("BasicCommands_ResetResource-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置属性的资源键 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_ResetResource_zh_CN {
            get {
                return ResourceManager.GetString("BasicCommands_ResetResource-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset Sharp Width 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_ResetWidth_en_US {
            get {
                return ResourceManager.GetString("BasicCommands_ResetWidth-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置形状宽度 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_ResetWidth_zh_CN {
            get {
                return ResourceManager.GetString("BasicCommands_ResetWidth-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Localization File 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_SelectLocalization_en_US {
            get {
                return ResourceManager.GetString("BasicCommands_SelectLocalization-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择本地化资源文件 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_SelectLocalization_zh_CN {
            get {
                return ResourceManager.GetString("BasicCommands_SelectLocalization-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send Backward 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_SendBackward_en_US {
            get {
                return ResourceManager.GetString("BasicCommands_SendBackward-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下移一层 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_SendBackward_zh_CN {
            get {
                return ResourceManager.GetString("BasicCommands_SendBackward-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send To Back 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_SendToBack_en_US {
            get {
                return ResourceManager.GetString("BasicCommands_SendToBack-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 置于底层 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_SendToBack_zh_CN {
            get {
                return ResourceManager.GetString("BasicCommands_SendToBack-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Data Command 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_UpdateCommand_en_US {
            get {
                return ResourceManager.GetString("BasicCommands_UpdateCommand-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新数据命令 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_UpdateCommand_zh_CN {
            get {
                return ResourceManager.GetString("BasicCommands_UpdateCommand-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Condition Model 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_UpdateCondition_en_US {
            get {
                return ResourceManager.GetString("BasicCommands_UpdateCondition-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新条件模型 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_UpdateCondition_zh_CN {
            get {
                return ResourceManager.GetString("BasicCommands_UpdateCondition-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Entity Model 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_UpdateEntity_en_US {
            get {
                return ResourceManager.GetString("BasicCommands_UpdateEntity-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新实体模型 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_UpdateEntity_zh_CN {
            get {
                return ResourceManager.GetString("BasicCommands_UpdateEntity-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh Table Info 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_UpdateTable_en_US {
            get {
                return ResourceManager.GetString("BasicCommands_UpdateTable-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新表结构 的本地化字符串。
        /// </summary>
        internal static string BasicCommands_UpdateTable_zh_CN {
            get {
                return ResourceManager.GetString("BasicCommands_UpdateTable-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Functions 的本地化字符串。
        /// </summary>
        internal static string Database_Functions_en_US {
            get {
                return ResourceManager.GetString("Database_Functions-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 函数 的本地化字符串。
        /// </summary>
        internal static string Database_Functions_zh_CN {
            get {
                return ResourceManager.GetString("Database_Functions-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tables 的本地化字符串。
        /// </summary>
        internal static string Database_Tables_en_US {
            get {
                return ResourceManager.GetString("Database_Tables-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表 的本地化字符串。
        /// </summary>
        internal static string Database_Tables_zh_CN {
            get {
                return ResourceManager.GetString("Database_Tables-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Views 的本地化字符串。
        /// </summary>
        internal static string Database_Views_en_US {
            get {
                return ResourceManager.GetString("Database_Views-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视图 的本地化字符串。
        /// </summary>
        internal static string Database_Views_zh_CN {
            get {
                return ResourceManager.GetString("Database_Views-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Support the validation attribute with conditional 的本地化字符串。
        /// </summary>
        internal static string DesignerValidation_BoolRequiredAttribute_en_US {
            get {
                return ResourceManager.GetString("DesignerValidation_BoolRequiredAttribute-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提供判断条件的必输验证特性。 的本地化字符串。
        /// </summary>
        internal static string DesignerValidation_BoolRequiredAttribute_zh_CN {
            get {
                return ResourceManager.GetString("DesignerValidation_BoolRequiredAttribute-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提供一个比较模型的两个属性的特性 的本地化字符串。
        /// </summary>
        internal static string DesignerValidation_CompareAttribute_en_US {
            get {
                return ResourceManager.GetString("DesignerValidation_CompareAttribute-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提供一个比较模型的两个属性的特性 的本地化字符串。
        /// </summary>
        internal static string DesignerValidation_CompareAttribute_zh_CN {
            get {
                return ResourceManager.GetString("DesignerValidation_CompareAttribute-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enum Type 的本地化字符串。
        /// </summary>
        internal static string DesignerValidation_EnumType_en_US {
            get {
                return ResourceManager.GetString("DesignerValidation_EnumType-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 枚举类型 的本地化字符串。
        /// </summary>
        internal static string DesignerValidation_EnumType_zh_CN {
            get {
                return ResourceManager.GetString("DesignerValidation_EnumType-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一条在验证失败的情况下与验证控件关联的错误消息。 的本地化字符串。
        /// </summary>
        internal static string DesignerValidation_ErrorMessage_en_US {
            get {
                return ResourceManager.GetString("DesignerValidation_ErrorMessage-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一条在验证失败的情况下与验证控件关联的错误消息。 的本地化字符串。
        /// </summary>
        internal static string DesignerValidation_ErrorMessage_zh_CN {
            get {
                return ResourceManager.GetString("DesignerValidation_ErrorMessage-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前设置是否需要生成属性的特性 的本地化字符串。
        /// </summary>
        internal static string DesignerValidation_IsGenerate_en_US {
            get {
                return ResourceManager.GetString("DesignerValidation_IsGenerate-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前设置是否需要生成属性的特性 的本地化字符串。
        /// </summary>
        internal static string DesignerValidation_IsGenerate_zh_CN {
            get {
                return ResourceManager.GetString("DesignerValidation_IsGenerate-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数组或字符串允许的最大长度 的本地化字符串。
        /// </summary>
        internal static string DesignerValidation_Length_en_US {
            get {
                return ResourceManager.GetString("DesignerValidation_Length-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数组或字符串允许的最大长度 的本地化字符串。
        /// </summary>
        internal static string DesignerValidation_Length_zh_CN {
            get {
                return ResourceManager.GetString("DesignerValidation_Length-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所允许的数据字段最大值 的本地化字符串。
        /// </summary>
        internal static string DesignerValidation_Maximum_en_US {
            get {
                return ResourceManager.GetString("DesignerValidation_Maximum-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所允许的数据字段最大值 的本地化字符串。
        /// </summary>
        internal static string DesignerValidation_Maximum_zh_CN {
            get {
                return ResourceManager.GetString("DesignerValidation_Maximum-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置字符串的最大长度 的本地化字符串。
        /// </summary>
        internal static string DesignerValidation_MaximumLength_en_US {
            get {
                return ResourceManager.GetString("DesignerValidation_MaximumLength-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置字符串的最大长度 的本地化字符串。
        /// </summary>
        internal static string DesignerValidation_MaximumLength_zh_CN {
            get {
                return ResourceManager.GetString("DesignerValidation_MaximumLength-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示数组或字符串允许的最大长度的特性 的本地化字符串。
        /// </summary>
        internal static string DesignerValidation_MaxLengthAttribute_en_US {
            get {
                return ResourceManager.GetString("DesignerValidation_MaxLengthAttribute-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示数组或字符串允许的最大长度的特性 的本地化字符串。
        /// </summary>
        internal static string DesignerValidation_MaxLengthAttribute_zh_CN {
            get {
                return ResourceManager.GetString("DesignerValidation_MaxLengthAttribute-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所允许的数据字段最小值 的本地化字符串。
        /// </summary>
        internal static string DesignerValidation_Minimum_en_US {
            get {
                return ResourceManager.GetString("DesignerValidation_Minimum-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所允许的数据字段最小值 的本地化字符串。
        /// </summary>
        internal static string DesignerValidation_Minimum_zh_CN {
            get {
                return ResourceManager.GetString("DesignerValidation_Minimum-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置字符串的最小长度 的本地化字符串。
        /// </summary>
        internal static string DesignerValidation_MinimumLength_en_US {
            get {
                return ResourceManager.GetString("DesignerValidation_MinimumLength-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置字符串的最小长度 的本地化字符串。
        /// </summary>
        internal static string DesignerValidation_MinimumLength_zh_CN {
            get {
                return ResourceManager.GetString("DesignerValidation_MinimumLength-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 比较运算符 的本地化字符串。
        /// </summary>
        internal static string DesignerValidation_Operator_en_US {
            get {
                return ResourceManager.GetString("DesignerValidation_Operator-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 比较运算符 的本地化字符串。
        /// </summary>
        internal static string DesignerValidation_Operator_zh_CN {
            get {
                return ResourceManager.GetString("DesignerValidation_Operator-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要与当前属性比较的属性名称 的本地化字符串。
        /// </summary>
        internal static string DesignerValidation_OtherProperty_en_US {
            get {
                return ResourceManager.GetString("DesignerValidation_OtherProperty-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要与当前属性比较的属性名称 的本地化字符串。
        /// </summary>
        internal static string DesignerValidation_OtherProperty_zh_CN {
            get {
                return ResourceManager.GetString("DesignerValidation_OtherProperty-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用于验证关联成员的正则表达式 的本地化字符串。
        /// </summary>
        internal static string DesignerValidation_Pattern_en_US {
            get {
                return ResourceManager.GetString("DesignerValidation_Pattern-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用于验证关联成员的正则表达式 的本地化字符串。
        /// </summary>
        internal static string DesignerValidation_Pattern_zh_CN {
            get {
                return ResourceManager.GetString("DesignerValidation_Pattern-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定用于验证关联成员的正则表达式 的本地化字符串。
        /// </summary>
        internal static string DesignerValidation_RegularExpressionAttribute_en_US {
            get {
                return ResourceManager.GetString("DesignerValidation_RegularExpressionAttribute-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定用于验证关联成员的正则表达式 的本地化字符串。
        /// </summary>
        internal static string DesignerValidation_RegularExpressionAttribute_zh_CN {
            get {
                return ResourceManager.GetString("DesignerValidation_RegularExpressionAttribute-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标属性为何值时，当前属性必输 的本地化字符串。
        /// </summary>
        internal static string DesignerValidation_RequiredValue_en_US {
            get {
                return ResourceManager.GetString("DesignerValidation_RequiredValue-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标属性为何值时，当前属性必输 的本地化字符串。
        /// </summary>
        internal static string DesignerValidation_RequiredValue_zh_CN {
            get {
                return ResourceManager.GetString("DesignerValidation_RequiredValue-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定数据字段中允许的最小和最大字符长度 的本地化字符串。
        /// </summary>
        internal static string DesignerValidation_StringLengthAttribute_en_US {
            get {
                return ResourceManager.GetString("DesignerValidation_StringLengthAttribute-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定数据字段中允许的最小和最大字符长度 的本地化字符串。
        /// </summary>
        internal static string DesignerValidation_StringLengthAttribute_zh_CN {
            get {
                return ResourceManager.GetString("DesignerValidation_StringLengthAttribute-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示需要比较的数据类型 的本地化字符串。
        /// </summary>
        internal static string DesignerValidation_ValidationDataType_en_US {
            get {
                return ResourceManager.GetString("DesignerValidation_ValidationDataType-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示需要比较的数据类型 的本地化字符串。
        /// </summary>
        internal static string DesignerValidation_ValidationDataType_zh_CN {
            get {
                return ResourceManager.GetString("DesignerValidation_ValidationDataType-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，该值指示数据字段处于编辑模式时，是否将 System.ComponentModel.DataAnnotations.DisplayFormatAttribute.DataFormatString 属性指定的格式设置字符串应用于字段值。 的本地化字符串。
        /// </summary>
        internal static string DisplayFormat_ApplyFormatInEditMode_en_US {
            get {
                return ResourceManager.GetString("DisplayFormat_ApplyFormatInEditMode-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，该值指示数据字段处于编辑模式时，是否将 System.ComponentModel.DataAnnotations.DisplayFormatAttribute.DataFormatString 属性指定的格式设置字符串应用于字段值。 的本地化字符串。
        /// </summary>
        internal static string DisplayFormat_ApplyFormatInEditMode_zh_CN {
            get {
                return ResourceManager.GetString("DisplayFormat_ApplyFormatInEditMode-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，该值指示在数据源中更新数据字段时是否将空字符串值 (&quot;&quot;) 自动转换为 null。 的本地化字符串。
        /// </summary>
        internal static string DisplayFormat_ConvertEmptyStringToNull_en_US {
            get {
                return ResourceManager.GetString("DisplayFormat_ConvertEmptyStringToNull-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，该值指示在数据源中更新数据字段时是否将空字符串值 (&quot;&quot;) 自动转换为 null。 的本地化字符串。
        /// </summary>
        internal static string DisplayFormat_ConvertEmptyStringToNull_zh_CN {
            get {
                return ResourceManager.GetString("DisplayFormat_ConvertEmptyStringToNull-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置字段值的显示格式。 的本地化字符串。
        /// </summary>
        internal static string DisplayFormat_DataFormatString_en_US {
            get {
                return ResourceManager.GetString("DisplayFormat_DataFormatString-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置字段值的显示格式。 的本地化字符串。
        /// </summary>
        internal static string DisplayFormat_DataFormatString_zh_CN {
            get {
                return ResourceManager.GetString("DisplayFormat_DataFormatString-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，该值指示字段是否应经过 HTML 编码。 的本地化字符串。
        /// </summary>
        internal static string DisplayFormat_HtmlEncode_en_US {
            get {
                return ResourceManager.GetString("DisplayFormat_HtmlEncode-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，该值指示字段是否应经过 HTML 编码。 的本地化字符串。
        /// </summary>
        internal static string DisplayFormat_HtmlEncode_zh_CN {
            get {
                return ResourceManager.GetString("DisplayFormat_HtmlEncode-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置字段值为 null 时为字段显示的文本。 的本地化字符串。
        /// </summary>
        internal static string DisplayFormat_NullDisplayText_en_US {
            get {
                return ResourceManager.GetString("DisplayFormat_NullDisplayText-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置字段值为 null 时为字段显示的文本。 的本地化字符串。
        /// </summary>
        internal static string DisplayFormat_NullDisplayText_zh_CN {
            get {
                return ResourceManager.GetString("DisplayFormat_NullDisplayText-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置属性的本地显示名称的转换器名称 的本地化字符串。
        /// </summary>
        internal static string DisplayName_ConverterName_en_US {
            get {
                return ResourceManager.GetString("DisplayName_ConverterName-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置属性的本地显示名称的转换器名称 的本地化字符串。
        /// </summary>
        internal static string DisplayName_ConverterName_zh_CN {
            get {
                return ResourceManager.GetString("DisplayName_ConverterName-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示属性的显示名称格式设置 的本地化字符串。
        /// </summary>
        internal static string DisplayName_Description_en_US {
            get {
                return ResourceManager.GetString("DisplayName_Description-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示属性的显示名称格式设置 的本地化字符串。
        /// </summary>
        internal static string DisplayName_Description_zh_CN {
            get {
                return ResourceManager.GetString("DisplayName_Description-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置属性的显示名称 的本地化字符串。
        /// </summary>
        internal static string DisplayName_DisplayName_en_US {
            get {
                return ResourceManager.GetString("DisplayName_DisplayName-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置属性的显示名称 的本地化字符串。
        /// </summary>
        internal static string DisplayName_DisplayName_zh_CN {
            get {
                return ResourceManager.GetString("DisplayName_DisplayName-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置显示特性的类型 的本地化字符串。
        /// </summary>
        internal static string DisplayName_DisplayType_en_US {
            get {
                return ResourceManager.GetString("DisplayName_DisplayType-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置显示特性的类型 的本地化字符串。
        /// </summary>
        internal static string DisplayName_DisplayType_zh_CN {
            get {
                return ResourceManager.GetString("DisplayName_DisplayType-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The call to GetDefaultExtension() has failed due to the exception: 的本地化字符串。
        /// </summary>
        internal static string GetDefaultExtensionFailed {
            get {
                return ResourceManager.GetString("GetDefaultExtensionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The call to GetDefaultExtension() has failed due to the exception: 的本地化字符串。
        /// </summary>
        internal static string GetDefaultExtensionFailed_en_US {
            get {
                return ResourceManager.GetString("GetDefaultExtensionFailed-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调用方法 GetDefaultExtension() 失败，异常信息: 的本地化字符串。
        /// </summary>
        internal static string GetDefaultExtensionFailed_zh_CN {
            get {
                return ResourceManager.GetString("GetDefaultExtensionFailed-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源信息 的本地化字符串。
        /// </summary>
        internal static string LocalizationResource_Category {
            get {
                return ResourceManager.GetString("LocalizationResource_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源信息 的本地化字符串。
        /// </summary>
        internal static string LocalizationResource_Category_en_US {
            get {
                return ResourceManager.GetString("LocalizationResource_Category-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源信息 的本地化字符串。
        /// </summary>
        internal static string LocalizationResource_Category_zh_CN {
            get {
                return ResourceManager.GetString("LocalizationResource_Category-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于资源的附加信息。此属性仅在设计时有意义。 的本地化字符串。
        /// </summary>
        internal static string LocalizationResource_Comment {
            get {
                return ResourceManager.GetString("LocalizationResource_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于资源的附加信息。此属性仅在设计时有意义。 的本地化字符串。
        /// </summary>
        internal static string LocalizationResource_Comment_en_US {
            get {
                return ResourceManager.GetString("LocalizationResource_Comment-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于资源的附加信息。此属性仅在设计时有意义。 的本地化字符串。
        /// </summary>
        internal static string LocalizationResource_Comment_zh_CN {
            get {
                return ResourceManager.GetString("LocalizationResource_Comment-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地化资源信息 的本地化字符串。
        /// </summary>
        internal static string LocalizationResource_CultureCategory {
            get {
                return ResourceManager.GetString("LocalizationResource_CultureCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地化资源信息 的本地化字符串。
        /// </summary>
        internal static string LocalizationResource_CultureCategory_en_US {
            get {
                return ResourceManager.GetString("LocalizationResource_CultureCategory-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地化资源信息 的本地化字符串。
        /// </summary>
        internal static string LocalizationResource_CultureCategory_zh_CN {
            get {
                return ResourceManager.GetString("LocalizationResource_CultureCategory-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于{0} 的本地化资源信息 的本地化字符串。
        /// </summary>
        internal static string LocalizationResource_CultureDescription {
            get {
                return ResourceManager.GetString("LocalizationResource_CultureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于{0} 的本地化资源信息 的本地化字符串。
        /// </summary>
        internal static string LocalizationResource_CultureDescription_en_US {
            get {
                return ResourceManager.GetString("LocalizationResource_CultureDescription-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于{0} 的本地化资源信息 的本地化字符串。
        /// </summary>
        internal static string LocalizationResource_CultureDescription_zh_CN {
            get {
                return ResourceManager.GetString("LocalizationResource_CultureDescription-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用于在代码中标识的资源分组名称。 的本地化字符串。
        /// </summary>
        internal static string LocalizationResource_Group {
            get {
                return ResourceManager.GetString("LocalizationResource_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用于在代码中标识的资源分组名称。 的本地化字符串。
        /// </summary>
        internal static string LocalizationResource_Group_en_US {
            get {
                return ResourceManager.GetString("LocalizationResource_Group-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用于在代码中标识的资源分组名称。 的本地化字符串。
        /// </summary>
        internal static string LocalizationResource_Group_zh_CN {
            get {
                return ResourceManager.GetString("LocalizationResource_Group-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用于在代码中标识的资源名称。 的本地化字符串。
        /// </summary>
        internal static string LocalizationResource_Name {
            get {
                return ResourceManager.GetString("LocalizationResource_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用于在代码中标识的资源名称。 的本地化字符串。
        /// </summary>
        internal static string LocalizationResource_Name_en_US {
            get {
                return ResourceManager.GetString("LocalizationResource_Name-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用于在代码中标识的资源名称。 的本地化字符串。
        /// </summary>
        internal static string LocalizationResource_Name_zh_CN {
            get {
                return ResourceManager.GetString("LocalizationResource_Name-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源值。 的本地化字符串。
        /// </summary>
        internal static string LocalizationResource_Value {
            get {
                return ResourceManager.GetString("LocalizationResource_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源值。 的本地化字符串。
        /// </summary>
        internal static string LocalizationResource_Value_en_US {
            get {
                return ResourceManager.GetString("LocalizationResource_Value-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源值。 的本地化字符串。
        /// </summary>
        internal static string LocalizationResource_Value_zh_CN {
            get {
                return ResourceManager.GetString("LocalizationResource_Value-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地化资源创建失败 的本地化字符串。
        /// </summary>
        internal static string Package_CreateResourceFailed {
            get {
                return ResourceManager.GetString("Package_CreateResourceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前数据持久类资源已经创建成功，且已经复制进系统剪贴板。 的本地化字符串。
        /// </summary>
        internal static string Package_CreateResourceSuccessful {
            get {
                return ResourceManager.GetString("Package_CreateResourceSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ASP.NET MVC Data Persistent 的本地化字符串。
        /// </summary>
        internal static string Package_Description_en_US {
            get {
                return ResourceManager.GetString("Package_Description-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ASP.NET MVC 数据持久类 的本地化字符串。
        /// </summary>
        internal static string Package_Description_zh_CN {
            get {
                return ResourceManager.GetString("Package_Description-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下列资源已经创建成功，且已经复制进系统剪贴板。 的本地化字符串。
        /// </summary>
        internal static string Package_ResourceDescription {
            get {
                return ResourceManager.GetString("Package_ResourceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property Attributes 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_Attributes_en_US {
            get {
                return ResourceManager.GetString("PersistentCategory_Attributes-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性特性 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_Attributes_zh_CN {
            get {
                return ResourceManager.GetString("PersistentCategory_Attributes-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check Command 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_CheckCommands_en_US {
            get {
                return ResourceManager.GetString("PersistentCategory_CheckCommands-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测命令 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_CheckCommands_zh_CN {
            get {
                return ResourceManager.GetString("PersistentCategory_CheckCommands-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CodeGenerator 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_CodeGenerator_en_US {
            get {
                return ResourceManager.GetString("PersistentCategory_CodeGenerator-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码生成 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_CodeGenerator_zh_CN {
            get {
                return ResourceManager.GetString("PersistentCategory_CodeGenerator-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collection List 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_Collections_en_US {
            get {
                return ResourceManager.GetString("PersistentCategory_Collections-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据集合列表 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_Collections_zh_CN {
            get {
                return ResourceManager.GetString("PersistentCategory_Collections-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Table Column 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_Column_en_US {
            get {
                return ResourceManager.GetString("PersistentCategory_Column-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库表列信息 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_Column_zh_CN {
            get {
                return ResourceManager.GetString("PersistentCategory_Column-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_Content_en_US {
            get {
                return ResourceManager.GetString("PersistentCategory_Content-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_Content_zh_CN {
            get {
                return ResourceManager.GetString("PersistentCategory_Content-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DataCommand 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_DataCommand_en_US {
            get {
                return ResourceManager.GetString("PersistentCategory_DataCommand-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据命令 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_DataCommand_zh_CN {
            get {
                return ResourceManager.GetString("PersistentCategory_DataCommand-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search Condition 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_DataCondition_en_US {
            get {
                return ResourceManager.GetString("PersistentCategory_DataCondition-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询条件类 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_DataCondition_zh_CN {
            get {
                return ResourceManager.GetString("PersistentCategory_DataCondition-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_Display_en_US {
            get {
                return ResourceManager.GetString("PersistentCategory_Display-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示格式 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_Display_zh_CN {
            get {
                return ResourceManager.GetString("PersistentCategory_Display-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dynamic Command 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_DynamicCommand_en_US {
            get {
                return ResourceManager.GetString("PersistentCategory_DynamicCommand-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动态命令 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_DynamicCommand_zh_CN {
            get {
                return ResourceManager.GetString("PersistentCategory_DynamicCommand-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Command 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_NewCommands_en_US {
            get {
                return ResourceManager.GetString("PersistentCategory_NewCommands-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新值命令 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_NewCommands_zh_CN {
            get {
                return ResourceManager.GetString("PersistentCategory_NewCommands-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_Parameter_en_US {
            get {
                return ResourceManager.GetString("PersistentCategory_Parameter-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令参数 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_Parameter_zh_CN {
            get {
                return ResourceManager.GetString("PersistentCategory_Parameter-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_Property_en_US {
            get {
                return ResourceManager.GetString("PersistentCategory_Property-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性 的本地化字符串。
        /// </summary>
        internal static string PersistentCategory_Property_zh_CN {
            get {
                return ResourceManager.GetString("PersistentCategory_Property-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置当前数据持久类需要继承的基类类型。 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_BaseAccess_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_BaseAccess-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置当前数据持久类需要继承的基类类型。 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_BaseAccess_zh_CN {
            get {
                return ResourceManager.GetString("PersistentDescription_BaseAccess-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测实体属性是否允许执行此命令，检测通过则允许执行，否则返回异常信息。 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_CheckCommand_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_CheckCommand-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测实体属性是否允许执行此命令，检测通过则允许执行，否则返回异常信息。 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_CheckCommand_zh_CN {
            get {
                return ResourceManager.GetString("PersistentDescription_CheckCommand-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets a value that indicates is a compute field 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_ColumnComputed_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_ColumnComputed-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，该值指示字段是否为计算列 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_ColumnComputed_zh_CN {
            get {
                return ResourceManager.GetString("PersistentDescription_ColumnComputed-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets a value that indicates is a DbTypeEnum of table&apos;s column 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_ColumnDbType_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_ColumnDbType-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置数据库字段的 DbType。 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_ColumnDbType_zh_CN {
            get {
                return ResourceManager.GetString("PersistentDescription_ColumnDbType-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets a value that indicates column name of entity&apos;s property  的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_ColumnName_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_ColumnName-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，该值指示实体属性所对应的字段名称 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_ColumnName_zh_CN {
            get {
                return ResourceManager.GetString("PersistentDescription_ColumnName-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the maximum number of digits used to represent the Value property. 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_ColumnPrecision_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_ColumnPrecision-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置列中数据的最大大小（以字节为单位） 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_ColumnPrecision_zh_CN {
            get {
                return ResourceManager.GetString("PersistentDescription_ColumnPrecision-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets a value, this value is primary key 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_ColumnPrimaryKey_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_ColumnPrimaryKey-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，该值指示字段是否为数据库表主键 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_ColumnPrimaryKey_zh_CN {
            get {
                return ResourceManager.GetString("PersistentDescription_ColumnPrimaryKey-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Table alias Name 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_ColumnProfix_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_ColumnProfix-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，该值指示字段所属表的别名 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_ColumnProfix_zh_CN {
            get {
                return ResourceManager.GetString("PersistentDescription_ColumnProfix-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the number of decimal places to which Value is resolved 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_ColumnScale_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_ColumnScale-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置数据库参数值解析为的小数位数 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_ColumnScale_zh_CN {
            get {
                return ResourceManager.GetString("PersistentDescription_ColumnScale-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the maximum size, in bytes, of the data within the column 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_ColumnSize_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_ColumnSize-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置列中数据的最大大小（以字节为单位） 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_ColumnSize_zh_CN {
            get {
                return ResourceManager.GetString("PersistentDescription_ColumnSize-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property Comment 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_Comment_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_Comment-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性描述 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_Comment_zh_CN {
            get {
                return ResourceManager.GetString("PersistentDescription_Comment-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前命令执行时需要传入的条件类实例。 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_DataConditionProperties_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_DataConditionProperties-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前命令执行时需要传入的条件类实例。 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_DataConditionProperties_zh_CN {
            get {
                return ResourceManager.GetString("PersistentDescription_DataConditionProperties-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置当前数据持久类的描述信息 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_Description_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_Description-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置当前数据持久类的描述信息 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_Description_zh_CN {
            get {
                return ResourceManager.GetString("PersistentDescription_Description-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体类文件所在的项目文件夹 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_EntityFolder_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_EntityFolder-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体类文件所在的项目文件夹 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_EntityFolder_zh_CN {
            get {
                return ResourceManager.GetString("PersistentDescription_EntityFolder-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置当前数据持久类，数据实体类的名称 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_EntityName_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_EntityName-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置当前数据持久类，数据实体类的名称 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_EntityName_zh_CN {
            get {
                return ResourceManager.GetString("PersistentDescription_EntityName-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体文件所在项目 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_EntityProject_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_EntityProject-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体文件所在项目 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_EntityProject_zh_CN {
            get {
                return ResourceManager.GetString("PersistentDescription_EntityProject-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体类初始化操作类型，默认为生成多个实体类。 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_Generate_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_Generate-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体类初始化操作类型，默认为生成多个实体类。 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_Generate_zh_CN {
            get {
                return ResourceManager.GetString("PersistentDescription_Generate-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置实体类的访问修饰符 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_Modifier_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_Modifier-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置实体类的访问修饰符 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_Modifier_zh_CN {
            get {
                return ResourceManager.GetString("PersistentDescription_Modifier-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从数据库中创建实体属性的新值。 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_NewCommand_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_NewCommand-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从数据库中创建实体属性的新值。 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_NewCommand_zh_CN {
            get {
                return ResourceManager.GetString("PersistentDescription_NewCommand-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示 DbCommand 的参数，也可以是它到 DataSet/DataTable 列的映射。 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_Parameter_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_Parameter-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示 DbCommand 的参数，也可以是它到 DataSet/DataTable 列的映射。 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_Parameter_zh_CN {
            get {
                return ResourceManager.GetString("PersistentDescription_Parameter-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示与 DbCommand 相关联的参数的集合以及各个参数到 DataSet/DataTable 中列的映射。 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_ParameterCollection_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_ParameterCollection-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示与 DbCommand 相关联的参数的集合以及各个参数到 DataSet/DataTable 中列的映射。 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_ParameterCollection_zh_CN {
            get {
                return ResourceManager.GetString("PersistentDescription_ParameterCollection-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comment for Property of entity  的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_PropertyComment_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_PropertyComment-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体属性的描述 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_PropertyComment_zh_CN {
            get {
                return ResourceManager.GetString("PersistentDescription_PropertyComment-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets a value that indicates whether the property accepts null values 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_PropertyDefaultValue_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_PropertyDefaultValue-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，该值指示实体属性的默认值 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_PropertyDefaultValue_zh_CN {
            get {
                return ResourceManager.GetString("PersistentDescription_PropertyDefaultValue-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is inheritance property. 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_PropertyInheritance_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_PropertyInheritance-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否为继承属性，如果是继承属性，则在当前类实例中不写入属性信息。 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_PropertyInheritance_zh_CN {
            get {
                return ResourceManager.GetString("PersistentDescription_PropertyInheritance-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the name of the dataentity&apos;s property 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_PropertyName_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_PropertyName-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，表示实体类中属性的名称 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_PropertyName_zh_CN {
            get {
                return ResourceManager.GetString("PersistentDescription_PropertyName-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets a value that indicates whether the property accepts null values 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_PropertyNullable_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_PropertyNullable-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，该值指示实体属性是否接受空值 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_PropertyNullable_zh_CN {
            get {
                return ResourceManager.GetString("PersistentDescription_PropertyNullable-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the type of the dataentity&apos;s property 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_PropertyType_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_PropertyType-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，表示实体类中属性的类型 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_PropertyType_zh_CN {
            get {
                return ResourceManager.GetString("PersistentDescription_PropertyType-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取当前数据持久类的表名称 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_TableName_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_TableName-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取当前数据持久类的表名称 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_TableName_zh_CN {
            get {
                return ResourceManager.GetString("PersistentDescription_TableName-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置当前数据持久类的视图名称 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_ViewName_en_US {
            get {
                return ResourceManager.GetString("PersistentDescription_ViewName-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置当前数据持久类的视图名称 的本地化字符串。
        /// </summary>
        internal static string PersistentDescription_ViewName_zh_CN {
            get {
                return ResourceManager.GetString("PersistentDescription_ViewName-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示验证特性集合 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_Attributes_en_US {
            get {
                return ResourceManager.GetString("PropertyDescription_Attributes-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示验证特性集合 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_Attributes_zh_CN {
            get {
                return ResourceManager.GetString("PropertyDescription_Attributes-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output display format 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_DataFormatString_en_US {
            get {
                return ResourceManager.GetString("PropertyDescription_DataFormatString-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出格式 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_DataFormatString_zh_CN {
            get {
                return ResourceManager.GetString("PropertyDescription_DataFormatString-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column Type 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_DbType_en_US {
            get {
                return ResourceManager.GetString("PropertyDescription_DbType-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段类型 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_DbType_zh_CN {
            get {
                return ResourceManager.GetString("PropertyDescription_DbType-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets a value that indicates whether the parameter is input-only, output-only, bidirectional, or a stored procedure return value parameter 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_Direction_en_US {
            get {
                return ResourceManager.GetString("PropertyDescription_Direction-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，该值指示参数是只可输入、只可输出、双向还是存储过程返回值参数 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_Direction_zh_CN {
            get {
                return ResourceManager.GetString("PropertyDescription_Direction-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specify how to display the data field and how to set the format of the data fields 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_DisplayFormat_en_US {
            get {
                return ResourceManager.GetString("PropertyDescription_DisplayFormat-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定如何显示数据字段以及如何设置数据字段的格式 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_DisplayFormat_zh_CN {
            get {
                return ResourceManager.GetString("PropertyDescription_DisplayFormat-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets namespace of the data persistent class&apos;s entity 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_EntityNamespace_en_US {
            get {
                return ResourceManager.GetString("PropertyDescription_EntityNamespace-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置当前数据持久类包含的实体类的命名空间 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_EntityNamespace_zh_CN {
            get {
                return ResourceManager.GetString("PropertyDescription_EntityNamespace-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the name of the dataentity 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_Name_en_US {
            get {
                return ResourceManager.GetString("PropertyDescription_Name-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，表示实体类名称 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_Name_zh_CN {
            get {
                return ResourceManager.GetString("PropertyDescription_Name-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets namespace of the data persistent class 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_NameSpace_en_US {
            get {
                return ResourceManager.GetString("PropertyDescription_NameSpace-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置当前数据持久类的命名空间 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_NameSpace_zh_CN {
            get {
                return ResourceManager.GetString("PropertyDescription_NameSpace-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets a value that indicates whether the parameter accepts null values 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_Nullable_en_US {
            get {
                return ResourceManager.GetString("PropertyDescription_Nullable-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，该值指示参数是否接受空值 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_Nullable_zh_CN {
            get {
                return ResourceManager.GetString("PropertyDescription_Nullable-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the name of the Parameter 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_ParameterName_en_US {
            get {
                return ResourceManager.GetString("PropertyDescription_ParameterName-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置 Parameter 的名称 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_ParameterName_zh_CN {
            get {
                return ResourceManager.GetString("PropertyDescription_ParameterName-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the DbType of the parameter 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_ParameterType_en_US {
            get {
                return ResourceManager.GetString("PropertyDescription_ParameterType-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置一个值，该值指示参数数据库参数的类型 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_ParameterType_zh_CN {
            get {
                return ResourceManager.GetString("PropertyDescription_ParameterType-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the maximum number of digits used to represent the Value property. 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_Precision_en_US {
            get {
                return ResourceManager.GetString("PropertyDescription_Precision-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置列中数据的最大大小（以字节为单位） 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_Precision_zh_CN {
            get {
                return ResourceManager.GetString("PropertyDescription_Precision-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_Property_en_US {
            get {
                return ResourceManager.GetString("PropertyDescription_Property-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_Property_zh_CN {
            get {
                return ResourceManager.GetString("PropertyDescription_Property-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the number of decimal places to which Value is resolved 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_Scale_en_US {
            get {
                return ResourceManager.GetString("PropertyDescription_Scale-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置数据库参数值解析为的小数位数 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_Scale_zh_CN {
            get {
                return ResourceManager.GetString("PropertyDescription_Scale-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the maximum size, in bytes, of the data within the column 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_Size_en_US {
            get {
                return ResourceManager.GetString("PropertyDescription_Size-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置列中数据的最大大小（以字节为单位） 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_Size_zh_CN {
            get {
                return ResourceManager.GetString("PropertyDescription_Size-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the name of the source column mapped to the DataSet/Entity and used for loading or returning the Value 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_SourceColumn_en_US {
            get {
                return ResourceManager.GetString("PropertyDescription_SourceColumn-en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取或设置源列的名称，该源列映射到 DataSet/Entity 并用于加载或返回 Value 的本地化字符串。
        /// </summary>
        internal static string PropertyDescription_SourceColumn_zh_CN {
            get {
                return ResourceManager.GetString("PropertyDescription_SourceColumn-zh-CN", resourceCulture);
            }
        }
    }
}
