//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basic.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Basic.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap AreaChartType {
            get {
                object obj = ResourceManager.GetObject("AreaChartType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap BarChartType {
            get {
                object obj = ResourceManager.GetObject("BarChartType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap BoxPlotChartType {
            get {
                object obj = ResourceManager.GetObject("BoxPlotChartType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap BubbleChartType {
            get {
                object obj = ResourceManager.GetObject("BubbleChartType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap CandleStickChartType {
            get {
                object obj = ResourceManager.GetObject("CandleStickChartType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ColumnChartType {
            get {
                object obj = ResourceManager.GetObject("ColumnChartType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Arguments 的本地化字符串。
        /// </summary>
        internal static string DataCommand_Arguments {
            get {
                return ResourceManager.GetString("DataCommand_Arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CheckCommands 的本地化字符串。
        /// </summary>
        internal static string DataCommand_CheckCommands {
            get {
                return ResourceManager.GetString("DataCommand_CheckCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NewCommands 的本地化字符串。
        /// </summary>
        internal static string DataCommand_NewCommands {
            get {
                return ResourceManager.GetString("DataCommand_NewCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameters 的本地化字符串。
        /// </summary>
        internal static string DataCommand_Parameters {
            get {
                return ResourceManager.GetString("DataCommand_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Properties 的本地化字符串。
        /// </summary>
        internal static string DataCommand_Properties {
            get {
                return ResourceManager.GetString("DataCommand_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon DataExplorerIcon_AggregateFunction {
            get {
                object obj = ResourceManager.GetObject("DataExplorerIcon_AggregateFunction", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon DataExplorerIcon_CheckConstraint {
            get {
                object obj = ResourceManager.GetObject("DataExplorerIcon_CheckConstraint", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon DataExplorerIcon_Column {
            get {
                object obj = ResourceManager.GetObject("DataExplorerIcon_Column", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon DataExplorerIcon_Component {
            get {
                object obj = ResourceManager.GetObject("DataExplorerIcon_Component", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon DataExplorerIcon_Connection {
            get {
                object obj = ResourceManager.GetObject("DataExplorerIcon_Connection", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon DataExplorerIcon_DataType {
            get {
                object obj = ResourceManager.GetObject("DataExplorerIcon_DataType", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon DataExplorerIcon_File {
            get {
                object obj = ResourceManager.GetObject("DataExplorerIcon_File", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon DataExplorerIcon_Folder {
            get {
                object obj = ResourceManager.GetObject("DataExplorerIcon_Folder", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon DataExplorerIcon_ForeignKey {
            get {
                object obj = ResourceManager.GetObject("DataExplorerIcon_ForeignKey", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon DataExplorerIcon_Index {
            get {
                object obj = ResourceManager.GetObject("DataExplorerIcon_Index", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon DataExplorerIcon_InputParameter {
            get {
                object obj = ResourceManager.GetObject("DataExplorerIcon_InputParameter", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon DataExplorerIcon_OutputParameter {
            get {
                object obj = ResourceManager.GetObject("DataExplorerIcon_OutputParameter", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon DataExplorerIcon_PrimaryKey {
            get {
                object obj = ResourceManager.GetObject("DataExplorerIcon_PrimaryKey", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon DataExplorerIcon_ReturnValue {
            get {
                object obj = ResourceManager.GetObject("DataExplorerIcon_ReturnValue", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon DataExplorerIcon_ScalarFunction {
            get {
                object obj = ResourceManager.GetObject("DataExplorerIcon_ScalarFunction", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon DataExplorerIcon_StoredProcedure {
            get {
                object obj = ResourceManager.GetObject("DataExplorerIcon_StoredProcedure", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon DataExplorerIcon_Table {
            get {
                object obj = ResourceManager.GetObject("DataExplorerIcon_Table", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon DataExplorerIcon_TabularFunction {
            get {
                object obj = ResourceManager.GetObject("DataExplorerIcon_TabularFunction", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon DataExplorerIcon_Trigger {
            get {
                object obj = ResourceManager.GetObject("DataExplorerIcon_Trigger", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon DataExplorerIcon_UniqueKey {
            get {
                object obj = ResourceManager.GetObject("DataExplorerIcon_UniqueKey", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon DataExplorerIcon_View {
            get {
                object obj = ResourceManager.GetObject("DataExplorerIcon_View", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap DoughnutChartType {
            get {
                object obj = ResourceManager.GetObject("DoughnutChartType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ErrorBarChartType {
            get {
                object obj = ResourceManager.GetObject("ErrorBarChartType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FastLineChartType {
            get {
                object obj = ResourceManager.GetObject("FastLineChartType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FastPointChartType {
            get {
                object obj = ResourceManager.GetObject("FastPointChartType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FunnelChartType {
            get {
                object obj = ResourceManager.GetObject("FunnelChartType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap GanttChartType {
            get {
                object obj = ResourceManager.GetObject("GanttChartType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap KagiChartType {
            get {
                object obj = ResourceManager.GetObject("KagiChartType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap LineChartType {
            get {
                object obj = ResourceManager.GetObject("LineChartType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap PieChartType {
            get {
                object obj = ResourceManager.GetObject("PieChartType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap PointAndFigureChartType {
            get {
                object obj = ResourceManager.GetObject("PointAndFigureChartType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap PointChartType {
            get {
                object obj = ResourceManager.GetObject("PointChartType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap PolarChartType {
            get {
                object obj = ResourceManager.GetObject("PolarChartType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 CodeGenerator 的本地化字符串。
        /// </summary>
        internal static string PropertyCategory_CodeGenerator {
            get {
                return ResourceManager.GetString("PropertyCategory_CodeGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content 的本地化字符串。
        /// </summary>
        internal static string PropertyCategory_Content {
            get {
                return ResourceManager.GetString("PropertyCategory_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DataCommand 的本地化字符串。
        /// </summary>
        internal static string PropertyCategory_DataCommand {
            get {
                return ResourceManager.GetString("PropertyCategory_DataCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap PyramidChartType {
            get {
                object obj = ResourceManager.GetObject("PyramidChartType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap RadarChartType {
            get {
                object obj = ResourceManager.GetObject("RadarChartType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap RangeChartType {
            get {
                object obj = ResourceManager.GetObject("RangeChartType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap RangeColumnChartType {
            get {
                object obj = ResourceManager.GetObject("RangeColumnChartType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap RenkoChartType {
            get {
                object obj = ResourceManager.GetObject("RenkoChartType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap SplineAreaChartType {
            get {
                object obj = ResourceManager.GetObject("SplineAreaChartType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap SplineChartType {
            get {
                object obj = ResourceManager.GetObject("SplineChartType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap SplineRangeChartType {
            get {
                object obj = ResourceManager.GetObject("SplineRangeChartType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap StackedAreaChartType {
            get {
                object obj = ResourceManager.GetObject("StackedAreaChartType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap StackedAreaChartType100 {
            get {
                object obj = ResourceManager.GetObject("StackedAreaChartType100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap StackedBarChartType {
            get {
                object obj = ResourceManager.GetObject("StackedBarChartType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap StackedBarChartType100 {
            get {
                object obj = ResourceManager.GetObject("StackedBarChartType100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap StackedColumnChartType {
            get {
                object obj = ResourceManager.GetObject("StackedColumnChartType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap StackedColumnChartType100 {
            get {
                object obj = ResourceManager.GetObject("StackedColumnChartType100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap StepLineChartType {
            get {
                object obj = ResourceManager.GetObject("StepLineChartType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap StockChartType {
            get {
                object obj = ResourceManager.GetObject("StockChartType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ThreeLineBreakChartType {
            get {
                object obj = ResourceManager.GetObject("ThreeLineBreakChartType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
