[assembly: System.Reflection.AssemblyCompany("SIP GoldSoft Technology Limited")]
//[assembly: System.Reflection.AssemblyCopyright("版权所有 (C) 苏州工业园区金软科技有限公司")]
//[assembly: System.Reflection.AssemblyTrademark("苏州工业园区金软科技有限公司基础框架")]
[assembly: System.Reflection.AssemblyCopyright("@SIP GoldSoft Technology Limited. All Rights Reserved.")]
[assembly: System.Reflection.AssemblyTrademark("Framework for .Net Standard 2.0 ")]
[assembly: System.Reflection.AssemblyVersion("6.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("6.0.0.0")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("6.0.5392")]
[assembly: System.Security.SecurityRules(System.Security.SecurityRuleSet.Level2, SkipVerificationInFullTrust = true)]